FROM mirror.gcr.io/library/node:22-slim
WORKDIR /app
ENV NODE_ENV=production

COPY node_modules ./node_modules
COPY artifacts/api-server/dist ./artifacts/api-server/dist
COPY artifacts/api-server/package.json ./artifacts/api-server/
COPY docs ./docs
COPY package.json ./

EXPOSE 8080
CMD ["node", "--enable-source-maps", "artifacts/api-server/dist/server/index.mjs"]
