// Shared automation-graph planner.
//
// This is the single engine that turns a plain-English request into a
// validated workflow graph. It is consumed by TWO surfaces:
//
//   1. POST /api/automations/assist  — the Automation Center drawer.
//   2. POST /api/ai-chat (Abby)      — the internal agent, via an
//      <automation_plan> action tag, so Abby has the SAME planning
//      capacity as the dedicated assistant.
//
// Keeping the logic here (instead of inline in the /assist route) means
// both callers share the exact same catalog summary, JSON/shape/catalog
// validation, recursive-retry perspective-shifting, and audit trail —
// there is no "second-class" planner.

import { z } from "zod/v4";
import { NODE_CATALOG, getNodeDefinition } from "./node-catalog";
import { callLLM } from "../ai-provider";
import { getAiConstitutionPreamble } from "../ai-constitution";
import {
  recursiveRetry,
  perspectiveCue,
  type AttemptOutcome,
  type AttemptLog,
  type StoppedReason,
} from "./recursive-retry";
import { logger } from "../logger";

// ── Schemas ────────────────────────────────────────────────────────────────

export const assistGraphSchema = z.object({
  nodes: z.array(z.object({
    // id is required, but accept numeric ids that some LLMs emit and coerce
    // to string so the editor's React Flow layer (which keys on string ids)
    // doesn't blow up downstream.
    id: z.union([z.string().min(1), z.number()]).transform((v) => String(v)),
    type: z.string().min(1),
    position: z.object({ x: z.number(), y: z.number() }).optional(),
    data: z.object({
      label: z.string().optional(),
      params: z.record(z.string(), z.any()).optional(),
    }).optional(),
  })).default([]),
  // Edge `id` is conventionally auto-generated by React Flow on the client,
  // so most LLMs (and most hand-authored examples) omit it. Accept missing
  // ids and synthesize a stable one from source→target so the editor and the
  // executor both have a unique key. Also accept numeric source/target ids.
  edges: z.array(z.object({
    id: z.string().min(1).optional(),
    source: z.union([z.string().min(1), z.number()]).transform((v) => String(v)),
    target: z.union([z.string().min(1), z.number()]).transform((v) => String(v)),
    sourceHandle: z.string().nullable().optional(),
    targetHandle: z.string().nullable().optional(),
  })).default([]).transform((edges) => {
    const seen = new Set<string>();
    return edges.map((e, i) => {
      let id = e.id ?? `e_${e.source}_${e.target}${e.sourceHandle ? `_${e.sourceHandle}` : ""}`;
      // De-dup if two edges resolve to the same synthesized id.
      while (seen.has(id)) id = `${id}_${i}`;
      seen.add(id);
      return { ...e, id };
    });
  }),
});

export type AssistGraph = z.infer<typeof assistGraphSchema>;

export const assistRequestSchema = z.object({
  prompt: z.string().min(3).max(4000),
  currentGraph: assistGraphSchema.optional(),
  mode: z.enum(["replace", "patch"]).default("replace"),
});

export type AssistRequest = z.infer<typeof assistRequestSchema>;

// ── Validation ───────────────────────────────────────────────────────────────

/**
 * Validate an assistant-produced graph against NODE_CATALOG. Returns the list
 * of issues; empty array means the graph is safe to surface to the editor.
 */
export function validateAssistGraph(
  graph: AssistGraph,
): { issues: string[]; warnings: string[] } {
  const issues: string[] = [];
  const warnings: string[] = [];
  const ids = new Set<string>();
  for (const n of graph.nodes) {
    if (ids.has(n.id)) { issues.push(`Duplicate node id "${n.id}".`); continue; }
    ids.add(n.id);
    const def = getNodeDefinition(n.type);
    if (!def) { issues.push(`Unknown node type "${n.type}" (id ${n.id}).`); continue; }
    // Param key allowlist: every key under data.params must correspond to a
    // declared NodeParamSpec for this node type. Unknown keys are STRIPPED
    // (not rejected) — LLMs occasionally leak edge-level fields like
    // `sourceHandle` into a node's params, or invent helper keys the
    // handler would silently ignore. Stripping keeps the workflow usable
    // and reports the dropped keys as warnings the operator can review.
    const declared = new Set(def.params.map((p) => p.key));
    const params = n.data?.params ?? {};
    const stripped: string[] = [];
    for (const key of Object.keys(params)) {
      if (!declared.has(key)) {
        delete (params as Record<string, unknown>)[key];
        stripped.push(key);
      }
    }
    if (stripped.length > 0) {
      warnings.push(`Node ${n.id} (${n.type}): stripped unknown params [${stripped.join(", ")}]. Allowed: [${def.params.map((p) => p.key).join(", ") || "—"}].`);
    }
  }
  for (const e of graph.edges) {
    if (!ids.has(e.source)) issues.push(`Edge ${e.id}: source "${e.source}" is not a node in this graph.`);
    if (!ids.has(e.target)) issues.push(`Edge ${e.id}: target "${e.target}" is not a node in this graph.`);
    if (e.sourceHandle) {
      const sourceNode = graph.nodes.find((n) => n.id === e.source);
      if (sourceNode) {
        const def = getNodeDefinition(sourceNode.type);
        const outs = def?.outputs;
        if (Array.isArray(outs) && !outs.includes(e.sourceHandle)) {
          issues.push(`Edge ${e.id}: sourceHandle "${e.sourceHandle}" is not declared on ${sourceNode.type} (allowed: ${outs.join(", ")}).`);
        }
      }
    }
  }
  return { issues, warnings };
}

/**
 * Compact catalog summary used in the assistant system prompt. Keeping it
 * tight so we don't burn tokens on every call. Outputs are listed verbatim
 * so the model knows the legal sourceHandle values for branching nodes.
 */
export function buildCatalogSummary(): string {
  const byCat: Record<string, string[]> = {};
  for (const def of NODE_CATALOG) {
    const outs = Array.isArray(def.outputs) ? `[${def.outputs.join("|")}]` : "*";
    // Render param keys as a plain comma-separated list. Earlier we appended
    // a trailing "!" to required keys, but several LLMs faithfully copied
    // the marker INTO the key name (e.g. emitted `"labels!": [...]`), which
    // then failed catalog validation. Required-ness is not enforced by
    // validateAssistGraph anyway; if a node truly needs a value the handler
    // will fail at run time with a helpful error.
    const required = def.params.filter((p) => p.required).map((p) => p.key);
    const optional = def.params.filter((p) => !p.required).map((p) => p.key);
    const parts: string[] = [];
    if (required.length) parts.push(`req=${required.join(",")}`);
    if (optional.length) parts.push(`opt=${optional.join(",")}`);
    const paramsStr = parts.length ? ` ${parts.join(" ")}` : "";
    (byCat[def.category] ??= []).push(`  ${def.type} ${outs}${paramsStr}`);
  }
  return Object.entries(byCat).map(([cat, lines]) => `[${cat}]\n${lines.join("\n")}`).join("\n");
}

// ── Planner ──────────────────────────────────────────────────────────────────

export type PlanOk = {
  ok: true;
  explanation: string;
  graph: AssistGraph;
  warnings: string[];
  attempts: AttemptLog[];
  stoppedReason: StoppedReason;
};

export type PlanErr = {
  ok: false;
  code: string;
  message: string;
  details?: unknown;
  attempts: AttemptLog[];
  stoppedReason: Exclude<StoppedReason, "succeeded">;
};

export type PlanResult = PlanOk | PlanErr;

function buildSystemPrompt(): string {
  const catalogSummary = buildCatalogSummary();
  const constitutionPreamble = getAiConstitutionPreamble();
  return [
    constitutionPreamble,
    "",
    "You are an expert workflow architect for MTOS Automation Center.",
    "Given a plain-English request, produce a workflow graph in JSON.",
    "STRICT RULES:",
    "- Output ONE JSON object only — no prose, no code fences.",
    `- Shape: { "explanation": string, "graph": { "nodes": [...], "edges": [...] } }`,
    "- Every node MUST use a `type` from the catalog below. Do not invent new types.",
    "- Every node needs `id` (unique short string), `type`, `position` ({x,y}), and `data.label`.",
    "- Put node-specific config under `data.params`.",
    "- Every workflow must start with exactly one trigger.* node.",
    "- For branching nodes (outputs listed as [a|b|c]), set edge `sourceHandle` to one of those names.",
    "- For non-branching nodes, omit sourceHandle.",
    "- Position nodes left-to-right with x increasing by ~220 per step, y around 200.",
    "- Edges are objects with `source` and `target` (node ids); `id` is optional and will be generated if omitted.",
    "",
    "CATALOG:",
    catalogSummary,
  ].join("\n");
}

/**
 * Turn a plain-English request into a validated workflow graph. Wraps the
 * LLM call in the recursive-retry perspective-shift loop and runs the full
 * JSON → shape → catalog validation ladder. NEVER throws — transport and
 * validation failures are returned as structured PlanErr so both HTTP and
 * chat callers can surface a useful message + the retry audit trail.
 */
export async function planAutomationGraph(
  input: AssistRequest,
  opts?: { maxAttempts?: number; maxTotalMs?: number },
): Promise<PlanResult> {
  const { prompt, currentGraph, mode } = input;
  const systemPrompt = buildSystemPrompt();

  const baseUserPrompt = [
    `User request: ${prompt}`,
    currentGraph
      ? `\nCurrent graph (mode=${mode}):\n${JSON.stringify(currentGraph).slice(0, 8_000)}`
      : "\n(No existing graph — build from scratch.)",
  ].join("\n");

  type AssistOk = { explanation: string; graph: AssistGraph; warnings: string[] };

  const runOneAttempt = async (
    ctx: { perspectiveIndex: number; totalAttempts: number; previousError: { code: string; message: string } | null },
  ): Promise<AttemptOutcome<AssistOk>> => {
    const cue = perspectiveCue(ctx.perspectiveIndex);
    const previousErrorBlock = ctx.previousError
      ? `\nPREVIOUS ATTEMPT FAILED:\n  code: ${ctx.previousError.code}\n  message: ${ctx.previousError.message.slice(0, 600)}\nAddress this in your next response.`
      : "";
    const attemptUserPrompt = [
      baseUserPrompt,
      cue ? `\n${cue}` : "",
      previousErrorBlock,
    ].filter(Boolean).join("\n");

    let raw: string;
    try {
      raw = await callLLM({
        module: "lead-intelligence",
        systemPrompt,
        prompt: attemptUserPrompt,
        maxTokens: 2500,
      });
    } catch (err: unknown) {
      return {
        ok: false,
        errorCode: "llm_unavailable",
        errorMessage: err instanceof Error ? err.message : "AI provider unreachable",
      };
    }

    // Strip code fences the model sometimes adds despite instructions.
    const cleaned = raw.trim().replace(/^```(?:json)?\s*/i, "").replace(/```$/m, "").trim();
    let payload: { explanation?: string; graph?: unknown };
    try {
      payload = JSON.parse(cleaned);
    } catch {
      return {
        ok: false,
        errorCode: "assist_invalid_json",
        errorMessage: "Assistant did not return valid JSON.",
        errorDetails: { raw: cleaned.slice(0, 800) },
      };
    }

    const graphParse = assistGraphSchema.safeParse(payload?.graph);
    if (!graphParse.success) {
      return {
        ok: false,
        errorCode: "assist_bad_shape",
        errorMessage: "Assistant produced a graph that does not match the expected shape.",
        errorDetails: graphParse.error.flatten(),
      };
    }

    const { issues, warnings } = validateAssistGraph(graphParse.data);
    if (issues.length > 0) {
      return {
        ok: false,
        errorCode: "assist_catalog_violation",
        errorMessage: `Graph uses unknown nodes or invalid edges: ${issues.slice(0, 3).map((x) => (typeof x === "string" ? x : JSON.stringify(x))).join("; ")}`,
        errorDetails: { issues, warnings, graph: graphParse.data },
      };
    }

    return {
      ok: true,
      value: {
        explanation: typeof payload.explanation === "string" ? payload.explanation : "",
        graph: graphParse.data,
        warnings,
      },
    };
  };

  const result = await recursiveRetry({
    attempt: runOneAttempt,
    // 4 total attempts (original + 3 retries). The hard ceiling in
    // recursive-retry.ts caps anything beyond 6.
    maxAttempts: opts?.maxAttempts ?? 4,
    // 30s wall-clock cap across all attempts.
    maxTotalMs: opts?.maxTotalMs ?? 30_000,
  });

  if (!result.ok) {
    logger.warn(
      { code: result.lastError.code, attempts: result.attempts.length, stoppedReason: result.stoppedReason },
      "planAutomationGraph: all retries failed",
    );
    return {
      ok: false,
      code: result.lastError.code,
      message: result.lastError.message,
      details: result.lastError.details,
      attempts: result.attempts,
      stoppedReason: result.stoppedReason,
    };
  }

  return {
    ok: true,
    explanation: result.value.explanation,
    graph: result.value.graph,
    warnings: result.value.warnings,
    attempts: result.attempts,
    stoppedReason: result.stoppedReason,
  };
}
