export interface IntegrationPreset {
  provider: string;
  name: string;
  type: string;
  category: string;
  description: string;
  docs_url: string;
  fields: Array<"api_key" | "api_url" | "webhook_url" | "account_sid" | "client_id" | "client_secret" | "access_id" | "access_password" | "fax_number" | "sender_email" | "from_email" | "from_name">;
  score: number;
  recommended?: boolean;
  pricing: "free" | "freemium" | "usage" | "subscription" | "enterprise";
  notes?: string;
}

export const PRESET_INTEGRATIONS: IntegrationPreset[] = [
  // ──────────────────────────── AI / LLM ENGINES ────────────────────────────
  { provider: "anthropic", name: "Anthropic Claude", type: "ai", category: "AI / LLM", description: "Claude models — best-in-class for long-context legal reasoning, drafting, and document review.", docs_url: "https://docs.anthropic.com", fields: ["api_key"], score: 10, recommended: true, pricing: "usage", notes: "Top pick for case summaries, demand letters, and intake script generation." },
  { provider: "openai", name: "OpenAI GPT", type: "ai", category: "AI / LLM", description: "GPT-4 / GPT-5 family — broadest ecosystem, strong tool use, multimodal vision.", docs_url: "https://platform.openai.com/docs", fields: ["api_key"], score: 9, recommended: true, pricing: "usage", notes: "Default safe choice; strongest plugin/tool-call ecosystem." },
  { provider: "google_gemini", name: "Google Gemini", type: "ai", category: "AI / LLM", description: "Gemini 2.5 Pro/Flash — massive context window, native multimodal, very cheap Flash tier.", docs_url: "https://ai.google.dev/docs", fields: ["api_key"], score: 9, pricing: "usage", notes: "Best price-per-token at scale; Flash is excellent for OCR + summarization." },
  { provider: "openrouter", name: "OpenRouter", type: "ai", category: "AI / LLM", description: "One API key, 200+ models from every major provider — switch models without re-coding.", docs_url: "https://openrouter.ai/docs", fields: ["api_key"], score: 9, recommended: true, pricing: "usage", notes: "Best for staying flexible. Recommended if you want to A/B test models." },
  { provider: "groq", name: "Groq", type: "ai", category: "AI / LLM", description: "Fastest inference on the market — Llama, Mixtral, Whisper at sub-second speeds.", docs_url: "https://console.groq.com/docs", fields: ["api_key"], score: 8, pricing: "usage", notes: "Use for real-time voice agents and streaming chat where latency matters." },
  { provider: "deepseek", name: "DeepSeek", type: "ai", category: "AI / LLM", description: "DeepSeek V3 / R1 — frontier reasoning at 1/10th the cost of GPT.", docs_url: "https://platform.deepseek.com", fields: ["api_key"], score: 8, pricing: "usage", notes: "Best price-to-performance for reasoning tasks." },
  { provider: "perplexity", name: "Perplexity", type: "ai", category: "AI / LLM", description: "Search-grounded LLM with live citations — ideal for legal research queries.", docs_url: "https://docs.perplexity.ai", fields: ["api_key"], score: 8, pricing: "usage", notes: "Use for research with sources, not general drafting." },
  { provider: "mistral", name: "Mistral AI", type: "ai", category: "AI / LLM", description: "EU-hosted frontier models — Mistral Large, Codestral. Sovereign AI option.", docs_url: "https://docs.mistral.ai", fields: ["api_key"], score: 7, pricing: "usage", notes: "Choose for EU data residency requirements." },
  { provider: "cohere", name: "Cohere", type: "ai", category: "AI / LLM", description: "Enterprise embeddings, reranking, and Command R+ for RAG pipelines.", docs_url: "https://docs.cohere.com", fields: ["api_key"], score: 7, pricing: "usage", notes: "Best-in-class reranker for case file search." },
  { provider: "xai_grok", name: "xAI Grok", type: "ai", category: "AI / LLM", description: "Grok-4 — real-time X (Twitter) data access, long context.", docs_url: "https://docs.x.ai", fields: ["api_key"], score: 6, pricing: "usage" },
  { provider: "fireworks_ai", name: "Fireworks AI", type: "ai", category: "AI / LLM", description: "Fast, cheap hosting of open-source models with fine-tuning.", docs_url: "https://docs.fireworks.ai", fields: ["api_key"], score: 7, pricing: "usage" },

  // ──────────────────────────── E-SIGNATURE ────────────────────────────
  { provider: "docusign", name: "DocuSign", type: "esign", category: "E-Signature", description: "Industry-standard e-signature — retainers, HIPAA authorizations, settlement docs.", docs_url: "https://developers.docusign.com", fields: ["api_key", "account_sid", "api_url"], score: 10, recommended: true, pricing: "subscription", notes: "Required by most insurance carriers and opposing counsel. The default for legal. Paste your DocuSign OAuth access token as api_key and your API Account ID as account_sid. For sandbox use api_url=https://demo.docusign.net/restapi." },
  { provider: "dropbox_sign", name: "Dropbox Sign (HelloSign)", type: "esign", category: "E-Signature", description: "Clean API, generous free tier, embedded signing flows.", docs_url: "https://developers.hellosign.com", fields: ["api_key"], score: 9, recommended: true, pricing: "freemium", notes: "Best DX for embedded retainer signing inside MTOS." },
  { provider: "pandadoc", name: "PandaDoc", type: "esign", category: "E-Signature", description: "Document automation + e-sign with rich templates and analytics.", docs_url: "https://developers.pandadoc.com", fields: ["api_key"], score: 8, pricing: "subscription", notes: "Strong for templated retainers with conditional logic." },
  { provider: "adobe_sign", name: "Adobe Acrobat Sign", type: "esign", category: "E-Signature", description: "Adobe ecosystem e-signature with PDF-native workflows.", docs_url: "https://opensource.adobe.com/acrobat-sign/", fields: ["api_key", "client_id", "client_secret"], score: 8, pricing: "subscription" },
  { provider: "signnow", name: "SignNow", type: "esign", category: "E-Signature", description: "Value-priced e-signature, white-label option.", docs_url: "https://docs.signnow.com", fields: ["api_key"], score: 7, pricing: "subscription" },
  { provider: "boldsign", name: "BoldSign", type: "esign", category: "E-Signature", description: "Developer-friendly e-sign with REST API and webhooks.", docs_url: "https://developers.boldsign.com", fields: ["api_key"], score: 7, pricing: "freemium" },
  { provider: "documenso", name: "Documenso", type: "esign", category: "E-Signature", description: "Open-source DocuSign alternative — self-host for full data control.", docs_url: "https://documenso.com/docs", fields: ["api_key", "api_url"], score: 6, pricing: "free" },

  // ──────────────────────────── VOICE AI AGENTS ────────────────────────────
  { provider: "vapi", name: "Vapi", type: "voice_ai", category: "Voice AI Agent", description: "Build production phone agents — inbound intake, outbound qualification, callbacks.", docs_url: "https://docs.vapi.ai", fields: ["api_key", "client_secret"], score: 9, recommended: true, pricing: "usage", notes: "api_key = Vapi server-side API key (also used to verify HMAC-SHA256 of webhook bodies). client_secret = the static bearer the assistant sends to /api/vapi-tools/* tool callbacks; if blank, tool callbacks are denied." },
  { provider: "retell_ai", name: "Retell AI", type: "voice_ai", category: "Voice AI Agent", description: "Sub-second latency voice agents with built-in turn detection.", docs_url: "https://docs.retellai.com", fields: ["api_key", "client_secret"], score: 9, recommended: true, pricing: "usage", notes: "api_key = Retell server-side key. client_secret = the webhook signing secret used to verify HMAC-SHA256 of inbound /api/webhooks/voice/retell_ai callbacks; if blank, status updates are dropped." },
  { provider: "bland_ai", name: "Bland AI", type: "voice_ai", category: "Voice AI Agent", description: "Phone-first AI agents — easiest setup, batched outbound campaigns.", docs_url: "https://docs.bland.ai", fields: ["api_key", "client_secret"], score: 8, pricing: "usage", notes: "api_key = Bland API key. client_secret = optional webhook signing secret (HMAC-SHA256 of rawBody). Without it, inbound webhooks are audit-only." },
  { provider: "elevenlabs", name: "ElevenLabs Conversational", type: "voice_ai", category: "Voice AI Agent", description: "Best-in-class voices + full conversational agent platform.", docs_url: "https://elevenlabs.io/docs", fields: ["api_key", "client_secret"], score: 8, recommended: true, pricing: "usage", notes: "api_key = ElevenLabs API key. client_secret = the webhook signing secret used to verify inbound /api/webhooks/voice/elevenlabs callbacks." },
  { provider: "synthflow", name: "Synthflow", type: "voice_ai", category: "Voice AI Agent", description: "No-code voice agent builder — fast to deploy, less customizable.", docs_url: "https://docs.synthflow.ai", fields: ["api_key", "client_secret"], score: 7, pricing: "subscription", notes: "api_key = Synthflow API key. client_secret = optional webhook signing secret; without it, inbound webhooks are audit-only." },

  // ──────────────────────────── SMS / TELEPHONY ────────────────────────────
  { provider: "twilio", name: "Twilio", type: "sms", category: "SMS & Telephony", description: "SMS, MMS, voice, WhatsApp — the gold standard. A2P 10DLC native.", docs_url: "https://www.twilio.com/docs", fields: ["api_key", "account_sid"], score: 10, recommended: true, pricing: "usage", notes: "Default choice. Use for client texting, callback queues, MFA." },
  { provider: "telnyx", name: "Telnyx", type: "sms", category: "SMS & Telephony", description: "Lower per-message pricing, BYOC SIP, strong programmable voice.", docs_url: "https://developers.telnyx.com", fields: ["api_key", "client_secret"], score: 8, pricing: "usage", notes: "api_key = Telnyx API v2 key (used to send outbound SMS). client_secret = the Telnyx public key used to verify Ed25519 signatures on inbound /api/webhooks/telnyx/sms callbacks; if blank, status updates are dropped." },
  { provider: "bandwidth", name: "Bandwidth", type: "sms", category: "SMS & Telephony", description: "Tier 1 carrier — best deliverability for high-volume A2P traffic.", docs_url: "https://dev.bandwidth.com", fields: ["api_key", "client_secret"], score: 8, pricing: "usage", notes: "api_key = Bandwidth API token. client_secret = the webhook callback secret used to verify HMAC-SHA256 of inbound delivery reports." },
  { provider: "plivo", name: "Plivo", type: "sms", category: "SMS & Telephony", description: "Twilio competitor with simpler pricing and strong global reach.", docs_url: "https://www.plivo.com/docs", fields: ["api_key", "account_sid"], score: 7, pricing: "usage" },
  { provider: "messagebird", name: "Bird (MessageBird)", type: "sms", category: "SMS & Telephony", description: "Omnichannel — SMS, WhatsApp, RCS, email in one platform.", docs_url: "https://docs.bird.com", fields: ["api_key", "client_secret"], score: 7, pricing: "usage", notes: "api_key = Bird API key. client_secret = the webhook signing key (HMAC-SHA256 of rawBody, with optional v2 timestamp prefix)." },
  { provider: "sinch", name: "Sinch", type: "sms", category: "SMS & Telephony", description: "Enterprise-scale CPaaS, owns Phaxio for fax.", docs_url: "https://developers.sinch.com", fields: ["api_key", "client_secret"], score: 7, pricing: "enterprise", notes: "api_key = Sinch service plan key. client_secret = the webhook signing secret used to verify inbound delivery reports." },

  // ──────────────────────────── EMAIL ────────────────────────────
  { provider: "sendgrid", name: "SendGrid", type: "email", category: "Email", description: "Twilio-owned email API — high deliverability, marketing + transactional.", docs_url: "https://docs.sendgrid.com", fields: ["api_key", "from_email", "from_name"], score: 9, recommended: true, pricing: "freemium", notes: "Default for transactional + drip campaigns. from_email must match a verified SendGrid Sender Identity." },
  { provider: "postmark", name: "Postmark", type: "email", category: "Email", description: "Best-in-class transactional deliverability, fast support.", docs_url: "https://postmarkapp.com/developer", fields: ["api_key"], score: 9, recommended: true, pricing: "usage", notes: "Use specifically for transactional (signed retainer confirmation, MFA). Inbox rate is unmatched." },
  { provider: "resend", name: "Resend", type: "email", category: "Email", description: "Modern email API for developers, beautiful React Email components.", docs_url: "https://resend.com/docs", fields: ["api_key"], score: 8, pricing: "freemium", notes: "Best DX; great for templated client emails." },
  { provider: "mailgun", name: "Mailgun", type: "email", category: "Email", description: "Mature transactional email with strong analytics and EU regions.", docs_url: "https://documentation.mailgun.com", fields: ["api_key"], score: 8, pricing: "usage" },
  { provider: "aws_ses", name: "AWS SES", type: "email", category: "Email", description: "Amazon Simple Email Service — cheapest at scale ($0.10 per 1k).", docs_url: "https://docs.aws.amazon.com/ses", fields: ["api_key", "client_secret"], score: 7, pricing: "usage", notes: "Use only if you already live in AWS; manual reputation warmup required." },
  { provider: "brevo", name: "Brevo (Sendinblue)", type: "email", category: "Email", description: "Email + SMS + CRM in one — generous free tier.", docs_url: "https://developers.brevo.com", fields: ["api_key"], score: 6, pricing: "freemium" },

  // ──────────────────────────── FAX (medical records) ────────────────────────────
  { provider: "srfax", name: "SRFax", type: "fax", category: "Fax", description: "HIPAA-compliant fax with healthcare focus. Includes a fax number — easiest setup for medical records requests.", docs_url: "https://www.srfax.com/api", fields: ["access_id", "access_password", "fax_number"], score: 9, recommended: true, pricing: "subscription" },
  { provider: "efax", name: "eFax Corporate", type: "fax", category: "Fax", description: "Legacy enterprise fax — still required by many older medical facilities.", docs_url: "https://www.efaxcorporate.com/api", fields: ["api_key"], score: 6, pricing: "subscription" },
  { provider: "phaxio", name: "Phaxio", type: "fax", category: "Fax", description: "Modern REST fax API with HIPAA BAA — fast onboarding.", docs_url: "https://www.phaxio.com/docs", fields: ["api_key", "client_secret"], score: 8, pricing: "usage", notes: "Use api_key + client_secret as Basic auth (Phaxio key + secret)." },
  { provider: "documo", name: "Documo (mFax)", type: "fax", category: "Fax", description: "HIPAA-compliant cloud fax with strong API and analytics.", docs_url: "https://docs.documo.com", fields: ["api_key"], score: 8, pricing: "subscription" },
  { provider: "telnyx_fax", name: "Telnyx Fax", type: "fax", category: "Fax", description: "Telnyx programmable fax — pairs naturally with Telnyx SMS/voice.", docs_url: "https://developers.telnyx.com/api/fax", fields: ["api_key", "fax_number"], score: 8, pricing: "usage" },

  // ──────────────────────────── MEDICAL RECORDS RETRIEVAL (AI) ────────────────────────────
  { provider: "datavant", name: "Datavant (Ciox Health)", type: "medical_records", category: "Medical Records Retrieval (AI)", description: "Largest medical records retrieval network in the US — used by 60%+ of plaintiff law firms. AI-powered indexing and chronology generation.", docs_url: "https://www.datavant.com/developers", fields: ["api_key", "client_secret"], score: 10, recommended: true, pricing: "usage", notes: "Industry standard for legal MRR. Direct connection to most US hospitals and providers. HIPAA BAA required." },
  { provider: "evenup", name: "EvenUp", type: "medical_records", category: "Medical Records Retrieval (AI)", description: "AI-powered medical record review and demand package generation for personal injury and mass tort firms.", docs_url: "https://www.evenuplaw.com", fields: ["api_key"], score: 9, recommended: true, pricing: "usage", notes: "Auto-generates demand letters and case chronologies from raw medical records. Built specifically for plaintiff PI/mass tort." },
  { provider: "supio", name: "Supio", type: "medical_records", category: "Medical Records Retrieval (AI)", description: "AI medical record summarization and timeline generation for plaintiff law firms.", docs_url: "https://www.supio.com", fields: ["api_key"], score: 9, pricing: "usage", notes: "Reads thousands of pages of records and produces searchable case timelines + ICD/CPT extraction." },
  { provider: "fasten_onprem", name: "Fasten On-Premise (Self-Hosted, Free)", type: "medical_records", category: "Medical Records Retrieval (AI)", description: "Self-hosted, GPL-licensed Fasten instance you run yourself. The recommended free path — no SaaS fees, full data residency, and the same patient-initiated FHIR aggregation across major US providers. Smaller catalog than the hosted Connect SaaS.", docs_url: "https://github.com/fastenhealth/fasten-onprem", fields: ["api_key"], score: 10, recommended: true, pricing: "free", notes: "Set api_url to your fasten-onprem base URL (e.g. https://fasten.your-domain.com). api_key = an admin API token issued by your fasten-onprem instance. Deploy fasten-onprem on Render/Fly/your own host — see https://github.com/fastenhealth/fasten-onprem for one-line Docker install." },
  { provider: "fasten_connect", name: "Fasten Connect (Hosted, Paid)", type: "medical_records", category: "Medical Records Retrieval (AI)", description: "Hosted SaaS variant of Fasten Health. Larger provider catalog (60k+) but requires a paid Fasten Developer Portal account. Prefer fasten_onprem unless you specifically need the wider catalog and managed infra.", docs_url: "https://docs.connect.fastenhealth.com", fields: ["api_key", "client_id", "client_secret"], score: 6, pricing: "usage", notes: "client_id = Public ID from the Fasten Developer Portal (public_test_… / public_live_…). api_key = Private key from the same portal. client_secret = the webhook signing secret printed once when you register your webhook URL (POST /api/webhooks/fasten). Set api_url to https://api.connect.fastenhealth.com (default) or the sandbox URL." },

  // ──────────────────────────── OCR / DOCUMENT AI ────────────────────────────
  { provider: "aws_textract", name: "AWS Textract", type: "ocr", category: "OCR & Document AI", description: "Best-in-class forms, tables, and signature extraction — HIPAA eligible.", docs_url: "https://docs.aws.amazon.com/textract", fields: ["api_key", "client_secret"], score: 9, recommended: true, pricing: "usage", notes: "Top pick for intake forms and structured medical records." },
  { provider: "google_document_ai", name: "Google Document AI", type: "ocr", category: "OCR & Document AI", description: "Pre-trained processors for medical records, invoices, IDs.", docs_url: "https://cloud.google.com/document-ai/docs", fields: ["api_key"], score: 9, recommended: true, pricing: "usage", notes: "Has dedicated medical-records-tuned models. Tied with Textract." },
  { provider: "azure_document_intelligence", name: "Azure Document Intelligence", type: "ocr", category: "OCR & Document AI", description: "Microsoft's OCR — strong layout understanding and prebuilt models.", docs_url: "https://learn.microsoft.com/azure/ai-services/document-intelligence/", fields: ["api_key", "api_url"], score: 8, pricing: "usage" },
  { provider: "mindee", name: "Mindee", type: "ocr", category: "OCR & Document AI", description: "Pre-built APIs for receipts, IDs, medical forms — fast integration.", docs_url: "https://developers.mindee.com", fields: ["api_key"], score: 8, pricing: "usage", notes: "Fastest path to production OCR if you don't want to train models." },
  { provider: "nanonets", name: "Nanonets", type: "ocr", category: "OCR & Document AI", description: "Custom OCR model training without ML expertise.", docs_url: "https://nanonets.com/documentation", fields: ["api_key"], score: 7, pricing: "subscription" },
  { provider: "tesseract_local", name: "Tesseract (local)", type: "ocr", category: "OCR & Document AI", description: "Free open-source OCR — already running in MTOS as fallback.", docs_url: "https://tesseract-ocr.github.io", fields: [], score: 5, pricing: "free", notes: "Already built-in. Good for low-stakes triage; cloud OCR is more accurate." },

  // ──────────────────────────── ADDRESS VALIDATION & GEO ────────────────────────────
  { provider: "smarty", name: "Smarty", type: "address", category: "Address & Geo", description: "USPS CASS-certified address verification + autocomplete. Fastest in the US.", docs_url: "https://www.smarty.com/docs", fields: ["api_key", "client_secret"], score: 9, recommended: true, pricing: "subscription", notes: "Default for US address validation in lead intake." },
  { provider: "lob", name: "Lob", type: "address", category: "Address & Geo", description: "Address verification + direct mail (settlement check delivery).", docs_url: "https://docs.lob.com", fields: ["api_key"], score: 8, pricing: "usage", notes: "Use if you also send physical mail." },
  { provider: "google_address_validation", name: "Google Address Validation", type: "address", category: "Address & Geo", description: "Google Maps platform — global coverage, geocoding, and place data.", docs_url: "https://developers.google.com/maps/documentation/address-validation", fields: ["api_key"], score: 8, pricing: "usage" },
  { provider: "melissa", name: "Melissa", type: "address", category: "Address & Geo", description: "Global address, name, phone, and email verification.", docs_url: "https://www.melissa.com/developer", fields: ["api_key"], score: 8, pricing: "usage" },
  { provider: "loqate", name: "Loqate", type: "address", category: "Address & Geo", description: "Global address verification by GBG — strong international.", docs_url: "https://www.loqate.com/resources/support/apis/", fields: ["api_key"], score: 7, pricing: "usage" },
  { provider: "usps_web_tools", name: "USPS Web Tools", type: "address", category: "Address & Geo", description: "Official USPS API — free, US-only, rate-limited.", docs_url: "https://www.usps.com/business/web-tools-apis/", fields: ["api_key"], score: 6, pricing: "free" },
  { provider: "mapbox", name: "Mapbox", type: "address", category: "Address & Geo", description: "Maps, geocoding, directions — designer-quality maps and pricing.", docs_url: "https://docs.mapbox.com", fields: ["api_key"], score: 9, pricing: "freemium", notes: "Best for any in-app mapping (vendor coverage zones, etc.)." },

  // ──────────────────────────── IDENTITY / KYC ────────────────────────────
  { provider: "persona", name: "Persona", type: "kyc", category: "Identity & KYC", description: "Flexible KYC — ID + selfie, government database checks, AML.", docs_url: "https://docs.withpersona.com", fields: ["api_key"], score: 9, recommended: true, pricing: "usage", notes: "Most flexible workflow builder; lawyer-friendly compliance." },
  { provider: "veriff", name: "Veriff", type: "kyc", category: "Identity & KYC", description: "Selfie + ID verification with strong fraud detection.", docs_url: "https://developers.veriff.com", fields: ["api_key"], score: 8, pricing: "usage" },
  { provider: "jumio", name: "Jumio", type: "kyc", category: "Identity & KYC", description: "Enterprise KYC — used by major banks and law firms.", docs_url: "https://www.jumio.com/api-documentation/", fields: ["api_key"], score: 8, pricing: "enterprise" },
  { provider: "onfido", name: "Onfido", type: "kyc", category: "Identity & KYC", description: "Global ID verification, especially strong outside US.", docs_url: "https://documentation.onfido.com", fields: ["api_key"], score: 8, pricing: "usage" },
  { provider: "socure", name: "Socure", type: "kyc", category: "Identity & KYC", description: "AI-driven identity decisioning — highest accuracy in US.", docs_url: "https://developer.socure.com", fields: ["api_key"], score: 7, pricing: "enterprise" },
  { provider: "trulioo", name: "Trulioo", type: "kyc", category: "Identity & KYC", description: "Global identity network — 195 countries.", docs_url: "https://developer.trulioo.com", fields: ["api_key"], score: 7, pricing: "usage" },

  // ──────────────────────────── BACKGROUND CHECKS ────────────────────────────
  { provider: "checkr", name: "Checkr", type: "background", category: "Background Check", description: "Modern background check API — criminal, MVR, employment.", docs_url: "https://docs.checkr.com", fields: ["api_key"], score: 9, recommended: true, pricing: "usage", notes: "Use for paralegal/staff onboarding and high-value claimant verification." },
  { provider: "sterling", name: "Sterling", type: "background", category: "Background Check", description: "Enterprise background screening with attorney-grade reports.", docs_url: "https://www.sterlingcheck.com/api", fields: ["api_key"], score: 8, pricing: "enterprise" },
  { provider: "truework", name: "Truework", type: "background", category: "Background Check", description: "Income and employment verification — useful for damages.", docs_url: "https://docs.truework.com", fields: ["api_key"], score: 7, pricing: "usage" },
  { provider: "goodhire", name: "GoodHire", type: "background", category: "Background Check", description: "Background checks tuned for small/mid law firms.", docs_url: "https://www.goodhire.com/api", fields: ["api_key"], score: 7, pricing: "usage" },

  // ──────────────────────────── PHONE VALIDATION & FRAUD ────────────────────────────
  { provider: "twilio_lookup", name: "Twilio Lookup", type: "phone_lookup", category: "Phone Validation & Fraud", description: "Line type, carrier, caller name, SIM swap detection.", docs_url: "https://www.twilio.com/docs/lookup/v2-api", fields: ["api_key", "account_sid"], score: 9, recommended: true, pricing: "usage", notes: "Filter VoIP and prepaid numbers in lead intake." },
  { provider: "telesign", name: "Telesign", type: "phone_lookup", category: "Phone Validation & Fraud", description: "Phone-based fraud scoring and verification.", docs_url: "https://developer.telesign.com", fields: ["api_key", "account_sid"], score: 8, pricing: "usage" },
  { provider: "ipqualityscore", name: "IPQualityScore", type: "phone_lookup", category: "Phone Validation & Fraud", description: "Phone, email, IP fraud scoring in one API.", docs_url: "https://www.ipqualityscore.com/documentation/overview", fields: ["api_key"], score: 7, pricing: "freemium" },
  { provider: "numverify", name: "NumVerify", type: "phone_lookup", category: "Phone Validation & Fraud", description: "Cheap basic phone validation — line type and carrier.", docs_url: "https://numverify.com/documentation", fields: ["api_key"], score: 6, pricing: "freemium" },

  // ──────────────────────────── COMPLIANCE / TCPA ────────────────────────────
  { provider: "blacklist_alliance", name: "Blacklist Alliance", type: "compliance", category: "TCPA Compliance", description: "Real-time TCPA litigator and DNC scrubbing.", docs_url: "https://www.blacklistalliance.com", fields: ["api_key", "api_url"], score: 9, recommended: true, pricing: "subscription", notes: "Industry standard for TCPA litigator scrubbing." },
  { provider: "tcpa_litigator_list", name: "TCPA Litigator List", type: "compliance", category: "TCPA Compliance", description: "Specialized TCPA litigator database.", docs_url: "https://www.tcpalitigatorlist.com", fields: ["api_key"], score: 8, pricing: "subscription" },
  { provider: "trustedform", name: "TrustedForm (ActiveProspect)", type: "compliance", category: "TCPA Compliance", description: "Lead consent certification — required by many TCPA-defensible carriers.", docs_url: "https://activeprospect.com/trustedform", fields: ["api_key"], score: 9, recommended: true, pricing: "usage", notes: "Already integrated in MTOS Form Engine." },
  { provider: "jornaya", name: "Jornaya (LeadiD)", type: "compliance", category: "TCPA Compliance", description: "Consumer journey tracking and consent capture.", docs_url: "https://www.jornaya.com", fields: ["api_key"], score: 8, pricing: "usage" },
  { provider: "dnc_scrub", name: "DNC.com", type: "compliance", category: "TCPA Compliance", description: "National DNC + state DNC scrubbing.", docs_url: "https://www.dnc.com/api", fields: ["api_key"], score: 7, pricing: "subscription" },

  // ──────────────────────────── STORAGE ────────────────────────────
  { provider: "aws_s3", name: "AWS S3", type: "storage", category: "File Storage", description: "Industry-standard object storage. HIPAA eligible with BAA.", docs_url: "https://docs.aws.amazon.com/s3", fields: ["api_key", "client_secret"], score: 10, recommended: true, pricing: "usage", notes: "Default for medical records and signed PDFs." },
  { provider: "cloudflare_r2", name: "Cloudflare R2", type: "storage", category: "File Storage", description: "S3-compatible storage with $0 egress fees — huge savings on downloads.", docs_url: "https://developers.cloudflare.com/r2", fields: ["api_key", "client_secret"], score: 9, recommended: true, pricing: "usage", notes: "Best value when staff/clients download files often." },
  { provider: "backblaze_b2", name: "Backblaze B2", type: "storage", category: "File Storage", description: "Cheapest S3-compatible storage. Great for archival.", docs_url: "https://www.backblaze.com/b2/docs/", fields: ["api_key", "client_secret"], score: 8, pricing: "usage" },
  { provider: "wasabi", name: "Wasabi", type: "storage", category: "File Storage", description: "S3-compatible, no egress fees, flat pricing.", docs_url: "https://docs.wasabi.com", fields: ["api_key", "client_secret"], score: 7, pricing: "usage" },
  { provider: "google_cloud_storage", name: "Google Cloud Storage", type: "storage", category: "File Storage", description: "GCS — pairs well with Google Document AI.", docs_url: "https://cloud.google.com/storage/docs", fields: ["api_key"], score: 8, pricing: "usage" },

  // ──────────────────────────── PAYMENTS ────────────────────────────
  { provider: "stripe", name: "Stripe", type: "payments", category: "Payments", description: "Best DX. Subscriptions, invoicing, ACH, dispute handling.", docs_url: "https://stripe.com/docs/api", fields: ["api_key", "client_secret"], score: 10, recommended: true, pricing: "usage", notes: "Default for SaaS billing if MTOS is multi-tenant." },
  { provider: "lawpay", name: "LawPay", type: "payments", category: "Payments", description: "Legal-industry payment processor — IOLTA-compliant trust account separation.", docs_url: "https://developers.affinipay.com", fields: ["api_key"], score: 9, recommended: true, pricing: "usage", notes: "Required if you handle client trust funds. Bar-association approved." },
  { provider: "square", name: "Square", type: "payments", category: "Payments", description: "Card-present + online payments, simple pricing.", docs_url: "https://developer.squareup.com", fields: ["api_key"], score: 8, pricing: "usage" },
  { provider: "authorize_net", name: "Authorize.Net", type: "payments", category: "Payments", description: "Long-standing payment gateway, widely accepted by legal vendors.", docs_url: "https://developer.authorize.net", fields: ["api_key", "client_secret"], score: 7, pricing: "subscription" },
  { provider: "paypal", name: "PayPal", type: "payments", category: "Payments", description: "Consumer-trusted alternative payment method.", docs_url: "https://developer.paypal.com", fields: ["api_key", "client_secret"], score: 6, pricing: "usage" },

  // ──────────────────────────── COURT RECORDS ────────────────────────────
  { provider: "pacer", name: "PACER (Federal Courts)", type: "court_records", category: "Court Records", description: "Public Access to Court Electronic Records — federal district, bankruptcy, and appellate cases via the PCL Search API.", docs_url: "https://pacer.uscourts.gov/help/pacer/case-search-only-api", fields: ["api_key", "client_secret"], score: 9, recommended: true, pricing: "usage", notes: "Save your PACER username as api_key and password as client_secret. Per-page billing applies on the PACER side. Powers the dedicated 'pacer_federal' lane in the Background Check Hub." },

  // ──────────────────────────── SEARCH APIs ────────────────────────────
  { provider: "serpapi", name: "SerpAPI", type: "search", category: "Web Search", description: "Google/Bing/Yahoo search results as structured JSON.", docs_url: "https://serpapi.com/search-api", fields: ["api_key"], score: 8, recommended: true, pricing: "subscription", notes: "Use for AI agents that need to research vendors or attorneys." },
  { provider: "tavily", name: "Tavily", type: "search", category: "Web Search", description: "AI-native search API — built for LLM agents.", docs_url: "https://tavily.com/docs", fields: ["api_key"], score: 8, pricing: "freemium" },
  { provider: "brave_search", name: "Brave Search", type: "search", category: "Web Search", description: "Independent index, privacy-focused, very cheap.", docs_url: "https://brave.com/search/api/", fields: ["api_key"], score: 7, pricing: "freemium" },
  { provider: "exa", name: "Exa", type: "search", category: "Web Search", description: "Semantic web search — find pages by meaning, not keyword.", docs_url: "https://docs.exa.ai", fields: ["api_key"], score: 7, pricing: "usage" },
  { provider: "bing_search", name: "Bing Search", type: "search", category: "Web Search", description: "Microsoft's search API.", docs_url: "https://learn.microsoft.com/bing/search-apis/", fields: ["api_key"], score: 6, pricing: "usage" },

  // ──────────────────────────── CALENDAR & SCHEDULING ────────────────────────────
  { provider: "calendly", name: "Calendly", type: "calendar", category: "Calendar & Scheduling", description: "Easiest scheduling tool — great for client consult booking.", docs_url: "https://developer.calendly.com", fields: ["api_key"], score: 9, recommended: true, pricing: "freemium", notes: "Default for attorney consult scheduling." },
  { provider: "cal_com", name: "Cal.com", type: "calendar", category: "Calendar & Scheduling", description: "Open-source, self-hostable Calendly alternative.", docs_url: "https://cal.com/docs", fields: ["api_key", "api_url"], score: 8, pricing: "freemium" },
  { provider: "google_calendar", name: "Google Calendar", type: "calendar", category: "Calendar & Scheduling", description: "Direct calendar sync for attorneys and paralegals.", docs_url: "https://developers.google.com/calendar", fields: ["client_id", "client_secret"], score: 9, pricing: "free" },
  { provider: "microsoft_graph", name: "Microsoft 365 (Graph)", type: "calendar", category: "Calendar & Scheduling", description: "Outlook calendar + Teams + email integration.", docs_url: "https://learn.microsoft.com/graph/", fields: ["client_id", "client_secret"], score: 8, pricing: "subscription" },
  { provider: "acuity", name: "Acuity Scheduling", type: "calendar", category: "Calendar & Scheduling", description: "Squarespace-owned scheduler with intake forms.", docs_url: "https://developers.acuityscheduling.com", fields: ["api_key"], score: 7, pricing: "subscription" },

  // ──────────────────────────── LEGAL CRM (existing) ────────────────────────────
  { provider: "clio", name: "Clio Manage", type: "crm", category: "Legal CRM", description: "Legal practice management — sync matters, contacts, billing.", docs_url: "https://app.clio.com/api/v4/documentation", fields: ["api_key", "api_url"], score: 9, recommended: true, pricing: "subscription", notes: "Most popular practice management software." },
  { provider: "filevine", name: "Filevine", type: "crm", category: "Legal CRM", description: "Legal project management and case tracking.", docs_url: "https://developer.filevine.io", fields: ["api_key", "api_url"], score: 9, recommended: true, pricing: "enterprise", notes: "Strongest for mass tort case management workflows." },
  { provider: "litify", name: "Litify", type: "crm", category: "Legal CRM", description: "Legal operations platform built on Salesforce.", docs_url: "https://litify.com", fields: ["api_key", "api_url"], score: 8, pricing: "enterprise" },
  { provider: "law_ruler", name: "Law Ruler", type: "crm", category: "Legal CRM", description: "Legal CRM — intake automation, lead tracking.", docs_url: "https://www.lawruler.com/integrations", fields: ["api_key", "api_url"], score: 8, pricing: "subscription" },
  { provider: "leaddocket", name: "Lead Docket", type: "crm", category: "Legal CRM", description: "Legal intake and lead management platform (Filevine company).", docs_url: "https://www.leaddocket.com", fields: ["api_key", "api_url"], score: 8, pricing: "subscription" },
  { provider: "casepeer", name: "CasePeer", type: "crm", category: "Legal CRM", description: "PI-focused practice management — strong intake, case tracking, settlements.", docs_url: "https://www.casepeer.com", fields: ["api_key", "api_url"], score: 9, recommended: true, pricing: "subscription", notes: "Top pick for personal injury and mass tort firms." },
  { provider: "smartadvocate", name: "SmartAdvocate", type: "crm", category: "Legal CRM", description: "Comprehensive case management for PI/mass tort with built-in workflow automation.", docs_url: "https://www.smartadvocate.com", fields: ["api_key", "api_url"], score: 8, pricing: "subscription" },
  { provider: "needles", name: "Needles (Trialworks)", type: "crm", category: "Legal CRM", description: "Long-standing case management for PI firms.", docs_url: "https://www.needleslaw.com", fields: ["api_key", "api_url"], score: 7, pricing: "subscription" },
  { provider: "smokeball", name: "Smokeball", type: "crm", category: "Legal CRM", description: "Cloud-based legal practice management.", docs_url: "https://www.smokeball.com", fields: ["api_key"], score: 7, pricing: "subscription" },
  { provider: "mycase", name: "MyCase", type: "crm", category: "Legal CRM", description: "Practice management — calendaring, billing, client portal.", docs_url: "https://www.mycase.com", fields: ["api_key"], score: 7, pricing: "subscription" },

  // ──────────────────────────── GENERAL CRM ────────────────────────────
  { provider: "hubspot", name: "HubSpot", type: "crm", category: "CRM", description: "Sync leads, contacts, and deals with HubSpot CRM.", docs_url: "https://developers.hubspot.com/docs/api", fields: ["api_key"], score: 9, recommended: true, pricing: "freemium" },
  { provider: "salesforce", name: "Salesforce", type: "crm", category: "CRM", description: "Enterprise CRM — leads, opportunities, custom objects.", docs_url: "https://developer.salesforce.com/docs/apis", fields: ["api_key", "api_url"], score: 9, pricing: "enterprise" },
  { provider: "pipedrive", name: "Pipedrive", type: "crm", category: "CRM", description: "Sales CRM and pipeline management.", docs_url: "https://developers.pipedrive.com/docs/api/v1", fields: ["api_key"], score: 7, pricing: "subscription" },

  // ──────────────────────────── DATA ENRICHMENT ────────────────────────────
  { provider: "lexisnexis", name: "LexisNexis", type: "enrichment", category: "Data Enrichment", description: "Legal research, identity, and risk assessment.", docs_url: "https://developer.lexisnexis.com", fields: ["api_key", "api_url"], score: 9, recommended: true, pricing: "enterprise", notes: "Industry standard for attorney research and case law." },
  { provider: "thomson_reuters_clear", name: "Thomson Reuters CLEAR", type: "enrichment", category: "Data Enrichment", description: "Investigative database — locate witnesses, verify identity.", docs_url: "https://legal.thomsonreuters.com/clear", fields: ["api_key"], score: 8, pricing: "enterprise" },
  { provider: "apollo_io", name: "Apollo.io", type: "enrichment", category: "Data Enrichment", description: "B2B contact data and outreach.", docs_url: "https://apolloio.github.io/apollo-api-docs/", fields: ["api_key"], score: 8, pricing: "subscription" },
  { provider: "zoominfo", name: "ZoomInfo", type: "enrichment", category: "Data Enrichment", description: "Premium B2B data — vendor and co-counsel research.", docs_url: "https://api-docs.zoominfo.com", fields: ["api_key"], score: 8, pricing: "enterprise" },
  { provider: "clearbit", name: "Clearbit (HubSpot)", type: "enrichment", category: "Data Enrichment", description: "Person and company enrichment by email.", docs_url: "https://dashboard.clearbit.com/docs", fields: ["api_key"], score: 7, pricing: "subscription" },

  // ──────────────────────────── AD PLATFORMS (lead gen) ────────────────────────────
  { provider: "meta_marketing", name: "Meta Marketing API", type: "ads", category: "Ad Platforms", description: "Facebook/Instagram lead ads — auto-pull leads into MTOS.", docs_url: "https://developers.facebook.com/docs/marketing-apis/", fields: ["client_id", "client_secret"], score: 9, recommended: true, pricing: "usage", notes: "Highest ROI lead source for most mass tort campaigns." },
  { provider: "google_ads", name: "Google Ads API", type: "ads", category: "Ad Platforms", description: "Search and YouTube lead campaigns.", docs_url: "https://developers.google.com/google-ads/api/docs", fields: ["client_id", "client_secret"], score: 9, recommended: true, pricing: "usage" },
  { provider: "tiktok_ads", name: "TikTok Marketing API", type: "ads", category: "Ad Platforms", description: "TikTok lead ads — strong for younger claimant pools.", docs_url: "https://business-api.tiktok.com/portal/docs", fields: ["client_id", "client_secret"], score: 7, pricing: "usage" },
  { provider: "linkedin_ads", name: "LinkedIn Ads", type: "ads", category: "Ad Platforms", description: "B2B targeting — useful for co-counsel referral campaigns.", docs_url: "https://learn.microsoft.com/linkedin/marketing/", fields: ["client_id", "client_secret"], score: 7, pricing: "usage" },

  // ──────────────────────────── AUTOMATION ────────────────────────────
  { provider: "zapier", name: "Zapier", type: "automation", category: "Automation", description: "Connect MTOS to 7,000+ apps via Zapier workflows.", docs_url: "https://zapier.com/apps", fields: ["api_key", "webhook_url"], score: 9, recommended: true, pricing: "freemium", notes: "Fastest path to integrate with anything not on this list." },
  { provider: "make", name: "Make (Integromat)", type: "automation", category: "Automation", description: "Visual workflow automation, more powerful than Zapier.", docs_url: "https://www.make.com/en/api-documentation", fields: ["api_key", "webhook_url"], score: 8, pricing: "freemium" },
  { provider: "n8n", name: "n8n", type: "automation", category: "Automation", description: "Open-source, self-hostable workflow automation.", docs_url: "https://docs.n8n.io", fields: ["api_key", "webhook_url"], score: 8, pricing: "free" },

  // ──────────────────────────── LEAD VENDORS / ROUTING ────────────────────────────
  { provider: "leadconduit", name: "LeadConduit (ActiveProspect)", type: "lead_vendor", category: "Lead Vendor & Routing", description: "Lead routing, scrubbing, and ping-post — industry standard.", docs_url: "https://activeprospect.com/products/leadconduit/", fields: ["api_key"], score: 9, recommended: true, pricing: "usage", notes: "Buy-side lead ops backbone." },
  { provider: "boberdoo", name: "Boberdoo", type: "lead_vendor", category: "Lead Vendor & Routing", description: "Sell-side lead distribution platform.", docs_url: "https://www.boberdoo.com", fields: ["api_key", "api_url"], score: 8, pricing: "subscription" },
  { provider: "ringba", name: "Ringba", type: "lead_vendor", category: "Lead Vendor & Routing", description: "Inbound call tracking and routing for pay-per-call.", docs_url: "https://ringba.com/docs/", fields: ["api_key"], score: 8, pricing: "usage", notes: "Default for pay-per-call lead vendors." },
  { provider: "retreaver", name: "Retreaver", type: "lead_vendor", category: "Lead Vendor & Routing", description: "Call tracking and intelligent call routing.", docs_url: "https://www.retreaver.com/api/", fields: ["api_key"], score: 7, pricing: "subscription" },
];
