import pino from "pino";

const isProduction = process.env.NODE_ENV === "production";

export const logger = pino({
  level: process.env.LOG_LEVEL ?? "info",
  redact: {
    paths: [
      "req.headers.authorization",
      "req.headers.cookie",
      "res.headers['set-cookie']",
      "*.password",
      "*.password_hash",
      "*.ssn",
      "*.last_4_ssn",
      "*.date_of_birth",
      "*.phone",
      "*.phone_primary",
      "*.street_address",
      "*.diagnosis",
      "*.diagnosis_date",
      "*.medications",
      "*.background_check_data",
      "*.encryption_key",
      "*.totp_secret",
      "*.totp_code",
      "*.refresh_token",
      "*.token",
      "*.access_token",
      "*.api_key",
      "*.webhook_hmac_secret",
      "*.client_secret",
      "*.email",
      "*.user_email",
      "*.first_name",
      "*.last_name",
      "*.physician_first_name",
      "*.physician_last_name",
      "*.physician_full_address",
      "*.physician_contact_info",
      "*.hospital_contact_info",
      "*.hospital_fax",
      "*.fromEmail",
      "*.from_email",
      "*.to",
      "*.toName",
      "*.to_name",
      "*.recipient",
      "*.recipients",
      "*.notes",
      "to",
      "toName",
      "to_name",
      "recipient",
      "recipients",
      "email",
      "phone",
    ],
    censor: "[REDACTED]",
  },
  ...(isProduction
    ? {}
    : {
        transport: {
          target: "pino-pretty",
          options: { colorize: true },
        },
      }),
});
