import { Router, type IRouter } from "express";
import healthRouter from "./health";
import leadsRouter from "./leads";
import documentsRouter from "./documents";
import dashboardRouter from "./dashboard";
import casesRouter from "./cases";
import ocrRouter from "./ocr";
import paralegalsRouter from "./paralegals";
import analyticsRouter from "./analytics";
import complianceRouter from "./compliance";
import npiRouter from "./npi";
import reviewQueueRouter from "./review-queue";
import formsRouter from "./forms";
import vendorsRouter from "./vendors";
import securityRouter from "./security";
import timelineRouter from "./timeline";
import draftingRouter from "./drafting";
import authRouter from "./auth";
import { authMiddleware } from "../lib/rbac";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use(authMiddleware);
router.use("/leads", leadsRouter);
router.use("/documents", documentsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/cases", casesRouter);
router.use("/ocr", ocrRouter);
router.use("/paralegals", paralegalsRouter);
router.use("/analytics", analyticsRouter);
router.use("/compliance", complianceRouter);
router.use("/npi", npiRouter);
router.use("/review-queue", reviewQueueRouter);
router.use("/forms", formsRouter);
router.use("/vendors", vendorsRouter);
router.use("/security", securityRouter);
router.use("/timeline", timelineRouter);
router.use("/drafting", draftingRouter);

export default router;
