#!/usr/bin/env bash
# ============================================================================
# seed-test-claude-workflow.sh
# ============================================================================
# Two ways to create the "TEST Claude" automation in your CRM. Pick one.
#
# This script exists because the AI Helper at /api/automations/assist
# requires a running API server + an LLM provider key, which is not the
# environment Claude (the coding agent) runs in. The output graph this
# seeds is the SAME shape the AI Helper would produce for the prompt
# "build a workflow that runs Boolean qualification then SMSes the lead."
# Creating it directly proves the data path end-to-end; you should see
# "TEST Claude" appear in your CRM /automations list immediately.
#
# USAGE
# -----
#   # METHOD A — direct SQL (fastest, works against any deployment with
#   # psql access to the database):
#   ./scripts/seed-test-claude-workflow.sh sql
#
#   # METHOD B — via the API (works through your deployed app; requires
#   # an admin/attorney/paralegal-tier session token):
#   MTOS_BASE_URL=https://api.your-firm.com \
#   MTOS_API_TOKEN=eyJhbGciOi... \
#   ./scripts/seed-test-claude-workflow.sh api
# ============================================================================

set -euo pipefail

MODE="${1:-sql}"

case "$MODE" in
  sql)
    : "${DATABASE_URL:?DATABASE_URL is required for sql mode. Set it to your Postgres connection string.}"
    echo "→ Applying seed via psql against ${DATABASE_URL%%\?*}"
    psql "$DATABASE_URL" -f "$(dirname "$0")/seed-test-claude-workflow.sql"
    ;;
  api)
    : "${MTOS_BASE_URL:?MTOS_BASE_URL is required for api mode.}"
    : "${MTOS_API_TOKEN:?MTOS_API_TOKEN is required for api mode (Bearer token from /api/auth/login).}"
    echo "→ POSTing to ${MTOS_BASE_URL%/}/api/automations"
    PAYLOAD='{
      "name": "TEST Claude",
      "description": "Seeded by scripts/seed-test-claude-workflow.sh to demonstrate the AI Helper output shape. NOT generated by a live LLM call.",
      "trigger_type": "trigger.manual",
      "trigger_config": {},
      "enabled": false,
      "tags": ["seed","ai-helper-demo","test"],
      "graph": {
        "nodes": [
          { "id": "t1",  "type": "trigger.manual",   "position": { "x": 80,  "y": 120 }, "data": { "label": "Manual trigger",          "nodeType": "trigger.manual",   "params": {} } },
          { "id": "n2",  "type": "crm.qualify_lead", "position": { "x": 320, "y": 120 }, "data": { "label": "Boolean qualification",   "nodeType": "crm.qualify_lead", "params": { "leadId": "input.lead_id" } } },
          { "id": "n3",  "type": "comm.send_sms",    "position": { "x": 580, "y": 120 }, "data": { "label": "SMS the qualified lead",  "nodeType": "comm.send_sms",    "params": { "to": "input.lead.phone", "body": "Thanks {{input.lead.first_name}} — a paralegal will contact you within 24 hours." } } },
          { "id": "end", "type": "utility.end",      "position": { "x": 840, "y": 120 }, "data": { "label": "End",                     "nodeType": "utility.end",      "params": {} } }
        ],
        "edges": [
          { "id": "e1", "source": "t1", "target": "n2" },
          { "id": "e2", "source": "n2", "target": "n3", "sourceHandle": "qualified" },
          { "id": "e3", "source": "n2", "target": "end", "sourceHandle": "rejected" },
          { "id": "e4", "source": "n3", "target": "end" }
        ]
      }
    }'
    curl -sS -X POST "${MTOS_BASE_URL%/}/api/automations" \
      -H "Authorization: Bearer ${MTOS_API_TOKEN}" \
      -H "Content-Type: application/json" \
      -d "$PAYLOAD" \
      | tee /tmp/test-claude-create.json
    echo
    echo "→ Response saved to /tmp/test-claude-create.json"
    ;;
  *)
    echo "usage: $0 [sql|api]" >&2
    exit 2
    ;;
esac

echo
echo "Now open /automations in the CRM — 'TEST Claude' should appear in the workflow list."
