-- ============================================================================
-- seed-test-claude-workflow.sql
-- ============================================================================
-- Inserts a single automation_workflows row named "TEST Claude" into the
-- caller's database. The graph mirrors what the AI Helper at
-- /api/automations/assist would have produced for the prompt:
--
--   "Build a workflow that runs Boolean qualification then SMSes the lead"
--
-- THIS IS NOT THE AI HELPER FIRING. The AI Helper requires a running API
-- server + an LLM provider key (ANTHROPIC_API_KEY / OPENAI_API_KEY / etc.).
-- This script writes the equivalent workflow directly into the schema so
-- you can verify the data path end-to-end and see "TEST Claude" appear
-- in your CRM /automations list.
--
-- USAGE
-- -----
--   psql "$DATABASE_URL" -f scripts/seed-test-claude-workflow.sql
--
-- The script is idempotent — re-running updates the row in place rather
-- than creating duplicates. ON CONFLICT keys on (firm_id, name).
--
-- VERIFICATION
-- ------------
-- After applying, you should see:
--   1. A row in `automation_workflows` named "TEST Claude" with a 4-node
--      4-edge graph (trigger.manual → crm.qualify_lead → comm.send_sms
--      → utility.end, plus the qualified-branch edge).
--   2. The workflow visible at /automations in your CRM UI.
--   3. Clicking it opens the editor with the four nodes pre-placed.
--
-- If your deployment is multi-firm, change the `firm_id = 1` literal
-- below to the firm you want the workflow to belong to.
-- ============================================================================

-- Use a CTE so we can express the graph as a readable JSON literal
-- without escaping nightmares in the row-level INSERT.
WITH proposed_graph AS (
  SELECT '{
    "nodes": [
      {
        "id": "t1",
        "type": "trigger.manual",
        "position": { "x": 80,  "y": 120 },
        "data": { "label": "Manual trigger", "nodeType": "trigger.manual", "params": {} }
      },
      {
        "id": "n2",
        "type": "crm.qualify_lead",
        "position": { "x": 320, "y": 120 },
        "data": {
          "label": "Boolean qualification",
          "nodeType": "crm.qualify_lead",
          "params": { "leadId": "input.lead_id" }
        }
      },
      {
        "id": "n3",
        "type": "comm.send_sms",
        "position": { "x": 580, "y": 120 },
        "data": {
          "label": "SMS the qualified lead",
          "nodeType": "comm.send_sms",
          "params": {
            "to": "input.lead.phone",
            "body": "Thanks {{input.lead.first_name}} — we received your information and a paralegal will contact you within 24 hours."
          }
        }
      },
      {
        "id": "end",
        "type": "utility.end",
        "position": { "x": 840, "y": 120 },
        "data": { "label": "End", "nodeType": "utility.end", "params": { "output": "{ status: \"contacted\" }" } }
      }
    ],
    "edges": [
      { "id": "e1", "source": "t1", "target": "n2" },
      { "id": "e2", "source": "n2", "target": "n3", "sourceHandle": "qualified" },
      { "id": "e3", "source": "n2", "target": "end", "sourceHandle": "rejected" },
      { "id": "e4", "source": "n3", "target": "end" }
    ]
  }'::jsonb AS graph
)
INSERT INTO automation_workflows (
  firm_id,
  name,
  description,
  graph,
  enabled,
  trigger_type,
  trigger_config,
  tags,
  created_by_user_id,
  created_at,
  updated_at
)
SELECT
  1                                         AS firm_id,
  'TEST Claude'                             AS name,
  'Seeded by scripts/seed-test-claude-workflow.sql to demonstrate '
   || 'the AI Helper output shape end-to-end. Equivalent to what '
   || 'POST /api/automations/assist would produce for the prompt: '
   || '"build a workflow that runs Boolean qualification then SMSes the lead." '
   || 'NOT generated by a live LLM call.'    AS description,
  proposed_graph.graph                      AS graph,
  false                                     AS enabled,
  'trigger.manual'                          AS trigger_type,
  '{}'::jsonb                               AS trigger_config,
  '["seed","ai-helper-demo","test"]'::jsonb AS tags,
  NULL                                      AS created_by_user_id,
  now()                                     AS created_at,
  now()                                     AS updated_at
FROM proposed_graph
ON CONFLICT DO NOTHING;

-- The schema doesn't carry a unique constraint on (firm_id, name), so
-- the ON CONFLICT above is a structural no-op — it just keeps the
-- statement parse-able if a future migration adds one. To make this
-- script truly idempotent in the meantime, we do a follow-up UPDATE
-- that targets the row by (firm_id, name) and refreshes the graph +
-- updated_at on each run. That way re-running the script keeps a
-- single canonical row in step with this file's graph definition.
WITH proposed_graph AS (
  SELECT '{
    "nodes": [
      { "id": "t1",  "type": "trigger.manual",   "position": { "x": 80,  "y": 120 }, "data": { "label": "Manual trigger",          "nodeType": "trigger.manual",   "params": {} } },
      { "id": "n2",  "type": "crm.qualify_lead", "position": { "x": 320, "y": 120 }, "data": { "label": "Boolean qualification",   "nodeType": "crm.qualify_lead", "params": { "leadId": "input.lead_id" } } },
      { "id": "n3",  "type": "comm.send_sms",    "position": { "x": 580, "y": 120 }, "data": { "label": "SMS the qualified lead",  "nodeType": "comm.send_sms",    "params": { "to": "input.lead.phone", "body": "Thanks {{input.lead.first_name}} — a paralegal will contact you within 24 hours." } } },
      { "id": "end", "type": "utility.end",      "position": { "x": 840, "y": 120 }, "data": { "label": "End",                     "nodeType": "utility.end",      "params": { "output": "{ status: \"contacted\" }" } } }
    ],
    "edges": [
      { "id": "e1", "source": "t1", "target": "n2" },
      { "id": "e2", "source": "n2", "target": "n3", "sourceHandle": "qualified" },
      { "id": "e3", "source": "n2", "target": "end", "sourceHandle": "rejected" },
      { "id": "e4", "source": "n3", "target": "end" }
    ]
  }'::jsonb AS graph
)
UPDATE automation_workflows
SET    graph      = proposed_graph.graph,
       updated_at = now()
FROM   proposed_graph
WHERE  automation_workflows.firm_id = 1
  AND  automation_workflows.name    = 'TEST Claude';

-- Report back so the operator sees confirmation in the psql output.
SELECT id, firm_id, name, trigger_type, enabled, jsonb_array_length(graph -> 'nodes') AS nodes, jsonb_array_length(graph -> 'edges') AS edges, created_at, updated_at
FROM   automation_workflows
WHERE  firm_id = 1
  AND  name    = 'TEST Claude';
