/**
 * Per-tort Vapi voice-agent provisioning service (Task #90).
 *
 * Idempotently creates/updates one Vapi assistant per tort:
 *   - create when the tort has no assistant yet
 *   - update when the generated prompt fingerprint changed (drift)
 *   - skip (in-sync) when the fingerprint matches and an assistant exists
 *
 * Resilient to partial failures across the batch: each tort succeeds or
 * fails independently and we always return honest per-tort status. The
 * tort_voice_agents table is the source of truth for sync metadata.
 *
 * Deterministic-first per the AI Constitution: the prompt is generated by
 * lib/voice/tort-agent-prompt.ts (pure string composition), not an LLM.
 */
import { createHash } from "node:crypto";
import { db, tortVoiceAgentsTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { logger } from "../logger";
import { resolveProvider, isResolved } from "../provider-router";
import { TORT_REGISTRY, type TortDefinition } from "../tort-engine";
import { buildTortAgentPrompt } from "./tort-agent-prompt";

const VAPI_BASE = "https://api.vapi.ai";

// Bump when the assistant payload contract changes (tool URL format, tool
// schema, model wiring) so every agent re-syncs even when the prompt text
// is unchanged. The stored fingerprint folds this version + the public API
// base + the prompt fingerprint, so drift is detected for ALL of: prompt
// edits, tool-wiring changes, and a newly-configured PUBLIC_API_BASE.
const TORT_AGENT_PAYLOAD_VERSION = "1.0.0";

/**
 * Composite fingerprint for drift detection. Covers the full provisioning
 * contract, not just the prompt: a change to the public API base (which
 * rewrites every tool callback URL) or a contract-version bump both force
 * a re-sync, closing the "wired-but-stale" gap.
 */
function computeAgentFingerprint(tort: TortDefinition): string {
  const prompt = buildTortAgentPrompt(tort);
  const apiBase = getPublicApiBase();
  return createHash("sha256")
    .update(`${TORT_AGENT_PAYLOAD_VERSION}|${apiBase}|${prompt.fingerprint}`)
    .digest("hex");
}

export type TortAgentSyncOutcome =
  | "created"
  | "updated"
  | "in_sync"
  | "error";

export interface TortAgentStatus {
  tort_id: string;
  tort_label: string;
  vapi_assistant_id: string | null;
  status: string;
  prompt_fingerprint: string | null;
  current_fingerprint: string;
  out_of_date: boolean;
  last_synced_at: string | null;
  last_error: string | null;
}

export interface TortAgentSyncResult {
  tort_id: string;
  tort_label: string;
  outcome: TortAgentSyncOutcome;
  vapi_assistant_id: string | null;
  error: string | null;
}

export interface VapiCreds {
  apiKey: string;
}

/**
 * Resolve the active Vapi api_key from the integrations vault via the
 * provider router. Returns a structured miss the caller can surface to
 * the operator rather than throwing.
 */
export async function resolveVapiApiKey(): Promise<
  { ok: true; apiKey: string } | { ok: false; code: string; message: string }
> {
  const resolved = await resolveProvider("voice");
  if (!isResolved(resolved)) {
    return {
      ok: false,
      code: "NO_VAPI",
      message: `Vapi voice provider not resolved: ${resolved.reason}${resolved.details ? ` — ${resolved.details}` : ""}`,
    };
  }
  if (resolved.provider !== "vapi") {
    return { ok: false, code: "NOT_VAPI", message: `Active voice provider is ${resolved.provider}, not vapi.` };
  }
  const creds = resolved.credentials as Record<string, unknown>;
  const apiKey = typeof creds.api_key === "string" ? creds.api_key.trim() : "";
  if (!apiKey) {
    return { ok: false, code: "NO_VAPI_KEY", message: "Vapi api_key missing from the integration." };
  }
  return { ok: true, apiKey };
}

/**
 * Build the Vapi assistant payload for a tort. The four tool callbacks
 * are wired via `server.url` + a fixed `tort_type` in the request body
 * so every tool call this agent makes is automatically tort-scoped.
 *
 * The public API base is read from PUBLIC_API_BASE (or REPLIT_DOMAINS /
 * deployment domain). Tool URLs point at /api/vapi-tools/<tool>.
 */
function getPublicApiBase(): string {
  const explicit = process.env["PUBLIC_API_BASE"]?.trim();
  if (explicit) return explicit.replace(/\/+$/, "");
  const domains = process.env["REPLIT_DOMAINS"]?.split(",")[0]?.trim();
  if (domains) return `https://${domains}`;
  return "";
}

/**
 * Define the four MTOS tool callbacks for a tort-scoped assistant.
 *
 * Tort scoping is done two ways for resilience:
 *   1. a `?tort=<id>` hint baked into each tool's server URL (the server
 *      reads it from the query string when the body omits tort_type), and
 *   2. a `tort_type` parameter pre-filled in the function schema so the
 *      model is steered to send it in the body too.
 * Either path yields the correct tort, so a single missing channel never
 * silently downgrades the agent to the generic "unknown" tort.
 */
function buildTortTools(tort: TortDefinition, apiBase: string): Record<string, unknown>[] {
  const toolUrl = (tool: string) =>
    `${apiBase}/api/vapi-tools/${tool}?tort=${encodeURIComponent(tort.id)}`;
  const tortParam = {
    type: "string",
    description: `Tort identifier. Always "${tort.id}" for this agent.`,
    default: tort.id,
  };
  const fn = (
    name: string,
    description: string,
    properties: Record<string, unknown>,
    required: string[],
  ) => ({
    type: "function",
    function: {
      name,
      description,
      parameters: { type: "object", properties: { ...properties, tort_type: tortParam }, required },
    },
    server: { url: toolUrl(name) },
  });

  return [
    fn(
      "lookup-lead",
      "Check whether a caller already exists by phone (and optional email).",
      {
        phone: { type: "string", description: "Caller phone number." },
        email: { type: "string", description: "Caller email, if known." },
      },
      ["phone"],
    ),
    fn(
      "create-lead",
      "Create a new lead for this tort once name and phone are collected.",
      {
        phone: { type: "string" },
        first_name: { type: "string" },
        last_name: { type: "string" },
        email: { type: "string" },
        date_of_birth: { type: "string" },
        notes: { type: "string" },
      },
      ["phone"],
    ),
    fn(
      "check-eligibility",
      "Run the deterministic eligibility check on a lead after collecting qualifying facts.",
      { lead_id: { type: "number", description: "The lead id returned by create-lead." } },
      ["lead_id"],
    ),
    fn(
      "escalate-to-human",
      "Hand off to a human reviewer when the situation is ambiguous or the caller is upset.",
      {
        lead_id: { type: "number" },
        call_id: { type: "string" },
        reason: { type: "string" },
      },
      [],
    ),
  ];
}

export function buildVapiAssistantPayload(tort: TortDefinition): Record<string, unknown> {
  const prompt = buildTortAgentPrompt(tort);
  const apiBase = getPublicApiBase();

  const bitdeerKey = process.env["BITDEER_API_KEY"]?.trim() ?? "";
  const tools = apiBase ? buildTortTools(tort, apiBase) : [];

  // Model: prefer BitDeer Qwen custom-llm (matches the existing generic
  // assistant); when no BitDeer key is present fall back to Vapi's default
  // OpenAI model so provisioning still works in a bare environment.
  const model: Record<string, unknown> = bitdeerKey
    ? {
        provider: "custom-llm",
        url: "https://api-inference.bitdeer.ai/v1/chat/completions",
        model: "Qwen/Qwen3-235B-A22B",
        authorizationHeader: `Bearer ${bitdeerKey}`,
        messages: [{ role: "system", content: prompt.systemPrompt }],
        ...(tools.length ? { tools } : {}),
      }
    : {
        provider: "openai",
        model: "gpt-4o-mini",
        messages: [{ role: "system", content: prompt.systemPrompt }],
        ...(tools.length ? { tools } : {}),
      };

  return {
    name: `MTOS — ${tort.label} (${tort.id})`,
    model,
    voice: { provider: "openai", voiceId: "alloy" },
    transcriber: { provider: "deepgram", model: "nova-2", language: "en-US" },
    firstMessage: prompt.firstMessage,
    endCallFunctionEnabled: true,
    recordingEnabled: true,
    metadata: { tort_id: tort.id, tort_label: tort.label },
  };
}

async function vapiFetch(
  apiKey: string,
  path: string,
  method: string,
  body?: unknown,
): Promise<{ ok: boolean; status: number; json: Record<string, unknown> }> {
  const resp = await fetch(`${VAPI_BASE}${path}`, {
    method,
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: body ? JSON.stringify(body) : undefined,
  });
  const json = (await resp.json().catch(() => ({}))) as Record<string, unknown>;
  return { ok: resp.ok, status: resp.status, json };
}

function resolveTort(tortId: string): TortDefinition | null {
  return TORT_REGISTRY[tortId] ?? null;
}

/**
 * Provision (create or update) a single tort agent. Idempotent:
 *   - no existing assistant  → create
 *   - fingerprint changed    → update
 *   - fingerprint unchanged  → in_sync (no Vapi call)
 */
export async function provisionTortAgent(tortId: string): Promise<TortAgentSyncResult> {
  const tort = resolveTort(tortId);
  if (!tort) {
    return { tort_id: tortId, tort_label: tortId, outcome: "error", vapi_assistant_id: null, error: "UNKNOWN_TORT" };
  }

  const keyResult = await resolveVapiApiKey();
  if (!keyResult.ok) {
    await upsertAgentRow(tort, { status: "error", last_error: keyResult.message });
    return { tort_id: tort.id, tort_label: tort.label, outcome: "error", vapi_assistant_id: null, error: keyResult.message };
  }

  // Tool callbacks are mandatory — a tort agent that cannot reach the 4
  // vapi-tools endpoints is not a functioning agent. Refuse to create or
  // update an assistant with no resolvable public API base rather than
  // provisioning a tools-less assistant and marking it "active".
  if (!getPublicApiBase()) {
    const msg =
      "PUBLIC_API_BASE not configured — cannot wire tool callbacks. Set PUBLIC_API_BASE (or REPLIT_DOMAINS) before provisioning.";
    await upsertAgentRow(tort, { status: "error", last_error: msg });
    return { tort_id: tort.id, tort_label: tort.label, outcome: "error", vapi_assistant_id: null, error: msg };
  }

  const fingerprint = computeAgentFingerprint(tort);
  const [existing] = await db
    .select()
    .from(tortVoiceAgentsTable)
    .where(eq(tortVoiceAgentsTable.tort_id, tort.id))
    .limit(1);

  // In-sync fast path: assistant exists and fingerprint matches.
  if (existing?.vapi_assistant_id && existing.prompt_fingerprint === fingerprint && existing.status === "active") {
    return {
      tort_id: tort.id,
      tort_label: tort.label,
      outcome: "in_sync",
      vapi_assistant_id: existing.vapi_assistant_id,
      error: null,
    };
  }

  const payload = buildVapiAssistantPayload(tort);

  try {
    let assistantId = existing?.vapi_assistant_id ?? null;
    let outcome: TortAgentSyncOutcome;

    if (assistantId) {
      // Update existing assistant (PATCH).
      const res = await vapiFetch(keyResult.apiKey, `/assistant/${assistantId}`, "PATCH", payload);
      if (!res.ok) {
        // If the assistant vanished upstream (404), fall back to create.
        if (res.status === 404) {
          assistantId = null;
        } else {
          throw new Error(`Vapi PATCH HTTP ${res.status}: ${JSON.stringify(res.json).slice(0, 200)}`);
        }
      } else {
        outcome = "updated";
      }
    }

    if (!assistantId) {
      const res = await vapiFetch(keyResult.apiKey, `/assistant`, "POST", payload);
      if (!res.ok || !res.json.id) {
        throw new Error(`Vapi POST HTTP ${res.status}: ${JSON.stringify(res.json).slice(0, 200)}`);
      }
      assistantId = String(res.json.id);
      outcome = "created";
    } else {
      outcome = "updated";
    }

    await upsertAgentRow(tort, {
      vapi_assistant_id: assistantId,
      status: "active",
      prompt_fingerprint: fingerprint,
      last_synced_at: new Date(),
      last_error: null,
    });

    logger.info({ tort_id: tort.id, assistantId, outcome }, "tort voice agent provisioned");
    return { tort_id: tort.id, tort_label: tort.label, outcome, vapi_assistant_id: assistantId, error: null };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    logger.error({ err, tort_id: tort.id }, "tort voice agent provisioning failed");
    await upsertAgentRow(tort, { status: "error", last_error: message });
    return { tort_id: tort.id, tort_label: tort.label, outcome: "error", vapi_assistant_id: existing?.vapi_assistant_id ?? null, error: message };
  }
}

async function upsertAgentRow(
  tort: TortDefinition,
  patch: Partial<typeof tortVoiceAgentsTable.$inferInsert>,
): Promise<void> {
  await db
    .insert(tortVoiceAgentsTable)
    .values({
      tort_id: tort.id,
      tort_label: tort.label,
      ...patch,
    })
    .onConflictDoUpdate({
      target: tortVoiceAgentsTable.tort_id,
      set: { tort_label: tort.label, ...patch, updated_at: new Date() },
    });
}

/**
 * Provision every tort in the registry. Each tort is attempted
 * independently; one failure never aborts the batch.
 */
export async function provisionAllTortAgents(): Promise<TortAgentSyncResult[]> {
  const results: TortAgentSyncResult[] = [];
  for (const tortId of Object.keys(TORT_REGISTRY)) {
    results.push(await provisionTortAgent(tortId));
  }
  return results;
}

/**
 * Read the per-tort status across all registry torts, joining the live
 * generated fingerprint against the stored one to flag drift.
 */
export async function listTortAgentStatus(): Promise<TortAgentStatus[]> {
  const rows = await db.select().from(tortVoiceAgentsTable);
  const byTort = new Map(rows.map((r) => [r.tort_id, r]));

  return Object.values(TORT_REGISTRY).map((tort) => {
    const fingerprint = computeAgentFingerprint(tort);
    const row = byTort.get(tort.id);
    const provisioned = !!row?.vapi_assistant_id && row.status === "active";
    const outOfDate = provisioned && row?.prompt_fingerprint !== fingerprint;
    return {
      tort_id: tort.id,
      tort_label: tort.label,
      vapi_assistant_id: row?.vapi_assistant_id ?? null,
      status: row?.status ?? "not_provisioned",
      prompt_fingerprint: row?.prompt_fingerprint ?? null,
      current_fingerprint: fingerprint,
      out_of_date: outOfDate,
      last_synced_at: row?.last_synced_at ? row.last_synced_at.toISOString() : null,
      last_error: row?.last_error ?? null,
    };
  });
}
