/**
 * Per-tort Vapi voice-agent provisioning service (Task #90).
 *
 * Idempotently creates/updates one Vapi assistant per tort:
 *   - create when the tort has no assistant yet
 *   - update when the generated prompt fingerprint changed (drift)
 *   - skip (in-sync) when the fingerprint matches and an assistant exists
 *
 * Resilient to partial failures across the batch: each tort succeeds or
 * fails independently and we always return honest per-tort status. The
 * tort_voice_agents table is the source of truth for sync metadata.
 *
 * Deterministic-first per the AI Constitution: the prompt is generated by
 * lib/voice/tort-agent-prompt.ts (pure string composition), not an LLM.
 */
import { createHash } from "node:crypto";
import { db, tortVoiceAgentsTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { logger } from "../logger";
import { resolveProvider, isResolved } from "../provider-router";
import { TORT_REGISTRY, type TortDefinition } from "../tort-engine";
import { buildTortAgentPrompt } from "./tort-agent-prompt";

const VAPI_BASE = "https://api.vapi.ai";

// Bump when the assistant payload contract changes (tool URL format, tool
// schema, model wiring) so every agent re-syncs even when the prompt text
// is unchanged. The stored fingerprint folds this version + the public API
// base + the prompt fingerprint, so drift is detected for ALL of: prompt
// edits, tool-wiring changes, and a newly-configured PUBLIC_API_BASE.
const TORT_AGENT_PAYLOAD_VERSION = "2.1.0";

/**
 * Composite fingerprint for drift detection. Covers the full provisioning
 * contract, not just the prompt: a change to the public API base (which
 * rewrites every tool callback URL) or a contract-version bump both force
 * a re-sync, closing the "wired-but-stale" gap.
 */
function computeAgentFingerprint(tort: TortDefinition): string {
  const prompt = buildTortAgentPrompt(tort);
  const apiBase = getPublicApiBase();
  return createHash("sha256")
    .update(`${TORT_AGENT_PAYLOAD_VERSION}|${apiBase}|${prompt.fingerprint}`)
    .digest("hex");
}

export type TortAgentSyncOutcome =
  | "created"
  | "updated"
  | "in_sync"
  | "error";

export interface TortAgentStatus {
  tort_id: string;
  tort_label: string;
  vapi_assistant_id: string | null;
  status: string;
  prompt_fingerprint: string | null;
  current_fingerprint: string;
  out_of_date: boolean;
  last_synced_at: string | null;
  last_error: string | null;
}

export interface TortAgentSyncResult {
  tort_id: string;
  tort_label: string;
  outcome: TortAgentSyncOutcome;
  vapi_assistant_id: string | null;
  error: string | null;
}

export interface VapiCreds {
  apiKey: string;
  toolBearer: string;
}

/**
 * Resolve the active Vapi credentials from the integrations vault via the
 * provider router. Both the api_key (used to call the Vapi management API)
 * and the tool bearer (`client_secret`, sent as `Authorization: Bearer` on
 * tool callbacks so they pass `checkBearer`) are read from the SAME resolved
 * integration row — this guarantees the assistant we create and the bearer
 * its callbacks present belong to one credential set, so multi-integration
 * setups can never create an assistant under one row and authenticate
 * callbacks against another. Returns a structured miss the caller can
 * surface to the operator rather than throwing.
 */
export async function resolveVapiApiKey(): Promise<
  { ok: true; apiKey: string; toolBearer: string } | { ok: false; code: string; message: string }
> {
  const resolved = await resolveProvider("voice");
  if (!isResolved(resolved)) {
    return {
      ok: false,
      code: "NO_VAPI",
      message: `Vapi voice provider not resolved: ${resolved.reason}${resolved.details ? ` — ${resolved.details}` : ""}`,
    };
  }
  if (resolved.provider !== "vapi") {
    return { ok: false, code: "NOT_VAPI", message: `Active voice provider is ${resolved.provider}, not vapi.` };
  }
  const creds = resolved.credentials as Record<string, unknown>;
  const apiKey = typeof creds.api_key === "string" ? creds.api_key.trim() : "";
  if (!apiKey) {
    return { ok: false, code: "NO_VAPI_KEY", message: "Vapi api_key missing from the integration." };
  }
  const toolBearer = typeof creds.client_secret === "string" ? creds.client_secret.trim() : "";
  if (!toolBearer) {
    return {
      ok: false,
      code: "NO_VAPI_TOOL_BEARER",
      message:
        "Vapi tool bearer (client_secret) missing from the integration — tool callbacks would be unauthenticated. Set the client_secret on the Vapi integration before provisioning.",
    };
  }
  return { ok: true, apiKey, toolBearer };
}

/**
 * Build the Vapi assistant payload for a tort. The four tool callbacks
 * are wired via `server.url` + a fixed `tort_type` in the request body
 * so every tool call this agent makes is automatically tort-scoped.
 *
 * The public API base is read from PUBLIC_API_BASE (or REPLIT_DOMAINS /
 * deployment domain). Tool URLs point at /api/vapi-tools/<tool>.
 */
function getPublicApiBase(): string {
  const explicit = process.env["PUBLIC_API_BASE"]?.trim();
  if (explicit) return explicit.replace(/\/+$/, "");
  const domains = process.env["REPLIT_DOMAINS"]?.split(",")[0]?.trim();
  if (domains) return `https://${domains}`;
  return "";
}

/**
 * Define the four MTOS tool callbacks for a tort-scoped assistant.
 *
 * Tort scoping is done two ways for resilience:
 *   1. a `?tort=<id>` hint baked into each tool's server URL (the server
 *      reads it from the query string when the body omits tort_type), and
 *   2. a `tort_type` parameter pre-filled in the function schema so the
 *      model is steered to send it in the body too.
 * Either path yields the correct tort, so a single missing channel never
 * silently downgrades the agent to the generic "unknown" tort.
 */
function buildTortTools(
  tort: TortDefinition,
  apiBase: string,
  toolBearer: string | null,
): Record<string, unknown>[] {
  const toolUrl = (tool: string) =>
    `${apiBase}/api/vapi-tools/${tool}?tort=${encodeURIComponent(tort.id)}`;
  // Every /api/vapi-tools/* callback is bearer-gated (checkBearer expects
  // `Authorization: Bearer <toolBearer>`). Bake that header into each tool's
  // server config so provisioned assistants authenticate; without it the
  // callbacks return 401 and the agent cannot look up / create leads.
  const serverHeaders = toolBearer ? { Authorization: `Bearer ${toolBearer}` } : undefined;
  const tortParam = {
    type: "string",
    description: `Tort identifier. Always "${tort.id}" for this agent.`,
    default: tort.id,
  };
  const fn = (
    name: string,
    description: string,
    properties: Record<string, unknown>,
    required: string[],
  ) => ({
    type: "function",
    function: {
      name,
      description,
      parameters: { type: "object", properties: { ...properties, tort_type: tortParam }, required },
    },
    server: serverHeaders ? { url: toolUrl(name), headers: serverHeaders } : { url: toolUrl(name) },
  });

  return [
    fn(
      "lookup-lead",
      "Check whether a caller already exists by phone (and optional email).",
      {
        phone: { type: "string", description: "Caller phone number." },
        email: { type: "string", description: "Caller email, if known." },
      },
      ["phone"],
    ),
    fn(
      "create-lead",
      "Create a new lead for this tort once name and phone are collected.",
      {
        phone: { type: "string" },
        first_name: { type: "string" },
        last_name: { type: "string" },
        email: { type: "string" },
        date_of_birth: { type: "string" },
        notes: { type: "string" },
      },
      ["phone"],
    ),
    fn(
      "update-lead",
      "Save the caller's answers to their lead AS SOON AS each one is confirmed, throughout the call. Call this repeatedly — send only the fields you just collected. Persisting progressively means nothing is lost if the call drops.",
      {
        lead_id: { type: "number", description: "The lead id returned by lookup-lead or create-lead." },
        first_name: { type: "string" },
        last_name: { type: "string" },
        email: { type: "string" },
        phone: { type: "string" },
        date_of_birth: { type: "string", description: "YYYY-MM-DD if known." },
        street_address: { type: "string" },
        city: { type: "string" },
        state: { type: "string", description: "2-letter state code." },
        zip: { type: "string" },
        diagnosis: { type: "string" },
        diagnosis_date: { type: "string" },
        exposure_start: { type: "string", description: "YYYY-MM-DD." },
        exposure_end: { type: "string", description: "YYYY-MM-DD." },
        location_name: { type: "string", description: "Place of exposure/use." },
        medications: { type: "string" },
        physician_first_name: { type: "string" },
        physician_last_name: { type: "string" },
        hospital_name: { type: "string" },
        notes: { type: "string", description: "Any other relevant detail." },
      },
      ["lead_id"],
    ),
    fn(
      "check-eligibility",
      "Run the deterministic eligibility check on a lead after collecting qualifying facts.",
      { lead_id: { type: "number", description: "The lead id returned by create-lead." } },
      ["lead_id"],
    ),
    fn(
      "escalate-to-human",
      "Hand off to a human reviewer when the situation is ambiguous or the caller is upset.",
      {
        lead_id: { type: "number" },
        call_id: { type: "string" },
        reason: { type: "string" },
      },
      [],
    ),
  ];
}

export function buildVapiAssistantPayload(
  tort: TortDefinition,
  toolBearer: string,
): Record<string, unknown> {
  const prompt = buildTortAgentPrompt(tort);
  const apiBase = getPublicApiBase();

  const tools = apiBase ? buildTortTools(tort, apiBase, toolBearer) : [];

  // Vapi's current API only accepts native model providers on the assistant
  // payload. An inline `authorizationHeader` for a custom-llm (e.g. BitDeer
  // Qwen) is rejected outright ("model.property authorizationHeader should not
  // exist"); wiring a custom LLM now requires a Vapi-stored credential
  // (POST /credential + credentialId), which is out of scope for basic per-tort
  // provisioning. Use Vapi's native OpenAI model so every tort agent provisions
  // and runs reliably. gpt-4o (over -mini) gives noticeably warmer, more
  // natural phrasing on these sensitive intake calls; a little temperature
  // keeps replies from sounding canned without loosening the deterministic
  // qualification gates (those live in the prompt, not the sampler).
  const model: Record<string, unknown> = {
    provider: "openai",
    model: "gpt-4o",
    temperature: 0.7,
    messages: [{ role: "system", content: prompt.systemPrompt }],
    ...(tools.length ? { tools } : {}),
  };

  // Vapi caps the assistant name at 40 chars. Keep it human-readable (the tort
  // label) and clamp; identity/lookup is driven by metadata + the
  // tort_voice_agents row, not the display name.
  const name = `MTOS ${tort.label}`.slice(0, 40);

  // Realism-tuned payload — the goal is an agent that sounds human and flows
  // naturally on the phone rather than reading a script:
  //   - voice: Cartesia (premium neural TTS) as primary instead of the robotic
  //     OpenAI "alloy", with an OpenAI fallback so a Cartesia hiccup never drops
  //     the call. This voiceId is one Vapi already validates for this account.
  //   - backchanneling: small spoken "mm-hmm"/"right" cues while the caller
  //     talks, so it feels like someone is actually listening.
  //   - startSpeakingPlan: smart endpointing + a short wait so the agent lets
  //     the caller finish a thought before replying (no clipping mid-sentence).
  //   - stopSpeakingPlan: natural barge-in — the caller can interrupt and the
  //     agent yields gracefully instead of talking over them.
  //   - backgroundDenoising: cleaner audio on noisy caller lines.
  // The transcriber is intentionally omitted so Vapi keeps its current
  // best-in-class default (multilingual streaming) rather than pinning an older
  // model and regressing existing assistants on re-sync.
  return {
    name,
    model,
    voice: {
      provider: "cartesia",
      voiceId: "57dcab65-68ac-45a6-8480-6c4c52ec1cd1",
      fallbackPlan: { voices: [{ provider: "openai", voiceId: "alloy" }] },
    },
    firstMessage: prompt.firstMessage,
    backchannelingEnabled: true,
    backgroundDenoisingEnabled: true,
    startSpeakingPlan: { waitSeconds: 0.4, smartEndpointingPlan: { provider: "vapi" } },
    stopSpeakingPlan: { numWords: 2, voiceSeconds: 0.2, backoffSeconds: 1.0 },
    endCallFunctionEnabled: true,
    recordingEnabled: true,
    metadata: { tort_id: tort.id, tort_label: tort.label },
  };
}

const VAPI_TIMEOUT_MS = 15000;
const VAPI_MAX_ATTEMPTS = 3;

function isTransientStatus(status: number): boolean {
  // Retry rate limits and upstream/server faults; never retry 4xx auth/
  // validation errors (they will fail identically) or 404 (caller handles
  // it as a recreate signal).
  return status === 429 || (status >= 500 && status <= 599);
}

const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

/**
 * Call the Vapi management API with a hard timeout and bounded retry/backoff
 * for transient failures (network errors, 429, 5xx). Non-transient HTTP
 * responses (including 404) are returned to the caller on the first attempt
 * so the provisioning state machine can react (e.g. 404 → recreate).
 */
async function vapiFetch(
  apiKey: string,
  path: string,
  method: string,
  body?: unknown,
): Promise<{ ok: boolean; status: number; json: Record<string, unknown> }> {
  let lastErr: unknown = null;
  for (let attempt = 1; attempt <= VAPI_MAX_ATTEMPTS; attempt++) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), VAPI_TIMEOUT_MS);
    try {
      const resp = await fetch(`${VAPI_BASE}${path}`, {
        method,
        headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
        body: body ? JSON.stringify(body) : undefined,
        signal: controller.signal,
      });
      const json = (await resp.json().catch(() => ({}))) as Record<string, unknown>;
      if (!resp.ok && isTransientStatus(resp.status) && attempt < VAPI_MAX_ATTEMPTS) {
        logger.warn(
          { path, method, status: resp.status, attempt },
          "vapi transient HTTP error — retrying",
        );
        await sleep(250 * 2 ** (attempt - 1));
        continue;
      }
      return { ok: resp.ok, status: resp.status, json };
    } catch (err) {
      // Network error or timeout (AbortError). Retry with backoff.
      lastErr = err;
      if (attempt < VAPI_MAX_ATTEMPTS) {
        logger.warn({ path, method, attempt, err }, "vapi network error — retrying");
        await sleep(250 * 2 ** (attempt - 1));
        continue;
      }
    } finally {
      clearTimeout(timer);
    }
  }
  const msg = lastErr instanceof Error ? lastErr.message : String(lastErr);
  throw new Error(`Vapi request failed after ${VAPI_MAX_ATTEMPTS} attempts: ${msg}`);
}

function resolveTort(tortId: string): TortDefinition | null {
  return TORT_REGISTRY[tortId] ?? null;
}

/**
 * Provision (create or update) a single tort agent. Idempotent:
 *   - no existing assistant  → create
 *   - fingerprint changed    → update
 *   - fingerprint unchanged  → in_sync (no Vapi call)
 */
export async function provisionTortAgent(tortId: string): Promise<TortAgentSyncResult> {
  const tort = resolveTort(tortId);
  if (!tort) {
    return { tort_id: tortId, tort_label: tortId, outcome: "error", vapi_assistant_id: null, error: "UNKNOWN_TORT" };
  }

  const keyResult = await resolveVapiApiKey();
  if (!keyResult.ok) {
    await upsertAgentRow(tort, { status: "error", last_error: keyResult.message });
    return { tort_id: tort.id, tort_label: tort.label, outcome: "error", vapi_assistant_id: null, error: keyResult.message };
  }

  // Tool callbacks are mandatory — a tort agent that cannot reach the 4
  // vapi-tools endpoints is not a functioning agent. Refuse to create or
  // update an assistant with no resolvable public API base rather than
  // provisioning a tools-less assistant and marking it "active".
  if (!getPublicApiBase()) {
    const msg =
      "PUBLIC_API_BASE not configured — cannot wire tool callbacks. Set PUBLIC_API_BASE (or REPLIT_DOMAINS) before provisioning.";
    await upsertAgentRow(tort, { status: "error", last_error: msg });
    return { tort_id: tort.id, tort_label: tort.label, outcome: "error", vapi_assistant_id: null, error: msg };
  }

  const fingerprint = computeAgentFingerprint(tort);
  const [existing] = await db
    .select()
    .from(tortVoiceAgentsTable)
    .where(eq(tortVoiceAgentsTable.tort_id, tort.id))
    .limit(1);

  // In-sync fast path: assistant exists and fingerprint matches.
  if (existing?.vapi_assistant_id && existing.prompt_fingerprint === fingerprint && existing.status === "active") {
    return {
      tort_id: tort.id,
      tort_label: tort.label,
      outcome: "in_sync",
      vapi_assistant_id: existing.vapi_assistant_id,
      error: null,
    };
  }

  const payload = buildVapiAssistantPayload(tort, keyResult.toolBearer);

  try {
    let assistantId = existing?.vapi_assistant_id ?? null;
    let outcome: TortAgentSyncOutcome;

    if (assistantId) {
      // Update existing assistant (PATCH).
      const res = await vapiFetch(keyResult.apiKey, `/assistant/${assistantId}`, "PATCH", payload);
      if (!res.ok) {
        // If the assistant vanished upstream (404), fall back to create.
        if (res.status === 404) {
          assistantId = null;
        } else {
          throw new Error(`Vapi PATCH HTTP ${res.status}: ${JSON.stringify(res.json).slice(0, 200)}`);
        }
      } else {
        outcome = "updated";
      }
    }

    if (!assistantId) {
      const res = await vapiFetch(keyResult.apiKey, `/assistant`, "POST", payload);
      if (!res.ok || !res.json.id) {
        throw new Error(`Vapi POST HTTP ${res.status}: ${JSON.stringify(res.json).slice(0, 200)}`);
      }
      assistantId = String(res.json.id);
      outcome = "created";
    } else {
      outcome = "updated";
    }

    await upsertAgentRow(tort, {
      vapi_assistant_id: assistantId,
      status: "active",
      prompt_fingerprint: fingerprint,
      last_synced_at: new Date(),
      last_error: null,
    });

    logger.info({ tort_id: tort.id, assistantId, outcome }, "tort voice agent provisioned");
    return { tort_id: tort.id, tort_label: tort.label, outcome, vapi_assistant_id: assistantId, error: null };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    logger.error({ err, tort_id: tort.id }, "tort voice agent provisioning failed");
    await upsertAgentRow(tort, { status: "error", last_error: message });
    return { tort_id: tort.id, tort_label: tort.label, outcome: "error", vapi_assistant_id: existing?.vapi_assistant_id ?? null, error: message };
  }
}

async function upsertAgentRow(
  tort: TortDefinition,
  patch: Partial<typeof tortVoiceAgentsTable.$inferInsert>,
): Promise<void> {
  await db
    .insert(tortVoiceAgentsTable)
    .values({
      tort_id: tort.id,
      tort_label: tort.label,
      ...patch,
    })
    .onConflictDoUpdate({
      target: tortVoiceAgentsTable.tort_id,
      set: { tort_label: tort.label, ...patch, updated_at: new Date() },
    });
}

/**
 * Provision every tort in the registry. Each tort is attempted
 * independently; one failure never aborts the batch.
 */
export async function provisionAllTortAgents(): Promise<TortAgentSyncResult[]> {
  const results: TortAgentSyncResult[] = [];
  for (const tortId of Object.keys(TORT_REGISTRY)) {
    results.push(await provisionTortAgent(tortId));
  }
  return results;
}

/**
 * Re-sync ONLY the agents currently flagged out_of_date (drifted fingerprint
 * on an otherwise-active assistant). Lets an operator act on stale agents in
 * bulk after a prompt/contract change without re-provisioning all torts.
 *
 * Each tort is attempted independently; one failure never aborts the batch.
 * The out-of-date set is read once up front via listTortAgentStatus so the
 * batch targets exactly what the UI showed the operator.
 */
export async function provisionOutOfDateTortAgents(): Promise<TortAgentSyncResult[]> {
  const statuses = await listTortAgentStatus();
  const staleTortIds = statuses.filter((s) => s.out_of_date).map((s) => s.tort_id);
  const results: TortAgentSyncResult[] = [];
  for (const tortId of staleTortIds) {
    results.push(await provisionTortAgent(tortId));
  }
  return results;
}

/**
 * Read the per-tort status across all registry torts, joining the live
 * generated fingerprint against the stored one to flag drift.
 */
export async function listTortAgentStatus(): Promise<TortAgentStatus[]> {
  const rows = await db.select().from(tortVoiceAgentsTable);
  const byTort = new Map(rows.map((r) => [r.tort_id, r]));

  return Object.values(TORT_REGISTRY).map((tort) => {
    const fingerprint = computeAgentFingerprint(tort);
    const row = byTort.get(tort.id);
    const provisioned = !!row?.vapi_assistant_id && row.status === "active";
    const outOfDate = provisioned && row?.prompt_fingerprint !== fingerprint;
    return {
      tort_id: tort.id,
      tort_label: tort.label,
      vapi_assistant_id: row?.vapi_assistant_id ?? null,
      status: row?.status ?? "not_provisioned",
      prompt_fingerprint: row?.prompt_fingerprint ?? null,
      current_fingerprint: fingerprint,
      out_of_date: outOfDate,
      last_synced_at: row?.last_synced_at ? row.last_synced_at.toISOString() : null,
      last_error: row?.last_error ?? null,
    };
  });
}
